"""Pure re-export facade. Source of truth lives in the `callbacks/` sub-package.
This notebook exists only to satisfy nbdev's export pipeline.
The generated `marisco/callbacks.py` is shadowed by `marisco/callbacks/` at runtime.

Docs: https://franckalbinet.github.io/mariscoapi/callbacks.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/callbacks.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/api/callbacks.ipynb #facade_exports
from .callbacks.core import *
from .callbacks.shared import *
from .callbacks.legacy import *

