"""Callbacks used by handlers to transform raw provider dataframes through an ordered pipeline of transformations.

Docs: https://franckalbinet.github.io/mariscoapi/callbacks.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/callbacks.ipynb.

# %% ../nbs/api/callbacks.ipynb #5a293345
from __future__ import annotations
import copy
from fastcore.all import *
from operator import attrgetter
from cftime import date2num ,num2date
import numpy as np
import pandas as pd
from typing import List, Dict, Callable, Any, Optional, Union
from collections import defaultdict
from .configs import get_lut, get_time_units, NC_GROUPS, SMP_TYPE_LUT
from pydantic import BaseModel, Field

# %% auto #0
__all__ = ['Callback', 'PerGroupCB', 'run_cbs', 'Transformer', 'SanitizeLonLatCB', 'RemapCB', 'SoftRemapCB', 'LowerStripNameCB',
           'AddSampleTypeIdColumnCB', 'RenameColumnsCB', 'RenameColsCB', 'RemoveAllNAValuesCB', 'MeltWideNuclidesCB',
           'SoftMeltWideNuclidesCB', 'AddSampleIDCB', 'CompareDfsAndTfmCB', 'UniqueIndexCB', 'ParseTimeCB',
           'EncodeTimeCB', 'DecodeTimeCB', 'SoftParseDateTimeCB', 'SoftConvertUnitCB', 'SoftRelToAbsUncCB',
           'SoftExtractUnitFromColCB', 'SoftShiftLonCB', 'SoftDMStoDecimalCB']

# %% ../nbs/api/callbacks.ipynb #4e58c73c
class Callback(): 
    "Base class for callbacks."
    order = 0
    def __init__(self): pass

# %% ../nbs/api/callbacks.ipynb #0414ac1d
class PerGroupCB(Callback):
    "Calls `each_grp` for each group in `tfm.dfs`; set `grps` to restrict to specific groups."
    grps: list = None

    def __init__(self,
                 grps: list=None  # Groups to process; None = all groups in `tfm.dfs`
                 ):
        if grps is not None: self.grps = grps

    def __call__(self, tfm):
        for grp in (self.grps or tfm.dfs):
            if grp in tfm.dfs: self.each_grp(grp, tfm.dfs[grp], tfm)

# %% ../nbs/api/callbacks.ipynb #92cf2c26
@patch
def each_grp(self:PerGroupCB,
             grp: str,          # Group key e.g. `'SEAWATER'`, `'BIOTA'`
             df: pd.DataFrame,  # DataFrame for this group
             tfm,               # Parent `Transformer`
             ):
    "Override to implement per-group transformation logic."
    raise NotImplementedError

# %% ../nbs/api/callbacks.ipynb #61702d17
def run_cbs(
    cbs: List[Callback], # List of callbacks to run
    obj: Any # Object to pass to the callbacks
    ):
    "Run the callbacks in the order they are specified."
    for cb in sorted(cbs, key=attrgetter('order')):
        if cb.__doc__: obj.logs.append(cb.__doc__)
        cb(obj)

# %% ../nbs/api/callbacks.ipynb #82a6611d
class Transformer():
    "Transform the dataframe(s) according to the specified callbacks."
    def __init__(self, 
                 data: Union[Dict[str, pd.DataFrame], pd.DataFrame], # Data to be transformed
                 cbs: Optional[List[Callback]]=None, # List of callbacks to run
                 custom_maps: Dict = None,
                 inplace: bool=False # Whether to modify the dataframe(s) in place
                 ): 
        store_attr()
        self.is_single_df = isinstance(data, pd.DataFrame)
        self.df, self.dfs = self._prepare_data(data, inplace)
        self.logs = []
        self.custom_maps = custom_maps or defaultdict(lambda: defaultdict(dict))
            
    def _prepare_data(self, data, inplace):
        if self.is_single_df:
            return (data if inplace else data.copy()), None
        else:
            return None, (data if inplace else {k: v.copy() for k, v in data.items()})
    
    def unique(self, col_name: str) -> np.ndarray:
        "Distinct values of a specific column present in all groups."
        if self.is_single_df:
            values = self.df.get(col_name, pd.Series()).dropna().values
        else:
            columns = [df.get(col_name) for df in self.dfs.values() if df.get(col_name) is not None]
            values = np.concatenate([col.dropna().values for col in columns]) if columns else []
        return np.unique(values)
        
    def __call__(self):
        "Transform the dataframe(s) according to the specified callbacks."
        if self.cbs: run_cbs(self.cbs, self)
        return self.df if self.dfs is None else self.dfs

# %% ../nbs/api/callbacks.ipynb #097d66b6
class SanitizeLonLatCB(PerGroupCB):
    "Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator."
    def __init__(self, 
                 lon_col: str='LON', # Longitude column name
                 lat_col: str='LAT', # Latitude column name
                 verbose: bool=False # Whether to print the number of invalid longitude & latitude values
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        df[self.lon_col] = df[self.lon_col].apply(lambda x: float(str(x).replace(',', '.')))
        df[self.lat_col] = df[self.lat_col].apply(lambda x: float(str(x).replace(',', '.')))
        mask_zeroes = (df[self.lon_col] == 0) & (df[self.lat_col] == 0)
        if mask_zeroes.sum() and self.verbose:
            print(f'The "{grp}" group contains {mask_zeroes.sum()} data points whose ({self.lon_col}, {self.lat_col}) = (0, 0)')
        mask_goob = (df[self.lon_col] < -180) | (df[self.lon_col] > 180) | (df[self.lat_col] < -90) | (df[self.lat_col] > 90)
        if mask_goob.sum() and self.verbose:
            print(f'The "{grp}" group contains {mask_goob.sum()} data points with unrealistic {self.lon_col} or {self.lat_col} values.')
        tfm.dfs[grp] = df.loc[~(mask_zeroes | mask_goob)]

# %% ../nbs/api/callbacks.ipynb #8c905654
class RemapCB(PerGroupCB):
    "Remap source values to MARIS standard identifiers using a lookup table."
    def __init__(self,
                 lut: dict|Callable,  # Lookup: dict, or callable(dfs)->dict
                 col_remap: str,            # Destination column to create
                 col_src: str,              # Source column with provider values
                 default_val: int=0,        # Value assigned to unmapped source values
                 grps: list[str]=None,      # Groups to process (None = all)
                ):
        store_attr()
        grp_str = ', '.join(str(g) for g in grps) if grps else 'all'
        self.__doc__ = f"Remap values from '{col_src}' to '{col_remap}' for groups: {grp_str}."

    def _resolve_lut(self, tfm):
        "Resolve the LUT: if a callable, call it with tfm's dfs to produce a dict."
        spec = self.lut
        if callable(spec):
            dfs = tfm.dfs if not tfm.is_single_df else {'_': tfm.df}
            spec = spec(dfs)
        return spec

    def __call__(self, tfm):
        self._resolved_lut = self._resolve_lut(tfm)
        super().__call__(tfm)

    def each_grp(self, grp, df, tfm):
        df[self.col_remap] = (df[self.col_src]
            .map(self._resolved_lut).fillna(self.default_val).astype(int))

# %% ../nbs/api/callbacks.ipynb #30153e7b
class SoftRemapCB(PerGroupCB):
    "Remap source tokens to MARIS IDs; lut=None/empty maps all tokens to default_val (Null-Object no-op)."
    class Schema(BaseModel):
        col_src:    str
        col_remap:  str
        lut:        dict[str, Any] = Field(default_factory=dict)
        default_val: Any           = 0

    def __init__(self,
                 col_src:     str,
                 col_remap:   str,
                 lut:         dict=None,
                 default_val: Any=0,
                 grps: list[str]=None,
                ):
        self.cfg  = self.Schema(col_src=col_src, col_remap=col_remap,
                                lut=lut or {}, default_val=default_val)
        self.grps = [None] if not self.cfg.lut else grps

    def each_grp(self, grp, df, tfm):
        df[self.cfg.col_remap] = (df[self.cfg.col_src]
            .map(self.cfg.lut).fillna(self.cfg.default_val).astype(int))

# %% ../nbs/api/callbacks.ipynb #bd1917a0
class LowerStripNameCB(PerGroupCB):
    "Convert values to lowercase and strip any trailing spaces."
    def __init__(self, 
                 col_src: str, # Source column name e.g. 'Nuclide'
                 col_dst: str=None, # Destination column name
                 fn_transform: Callable=lambda x: x.lower().strip() # Transformation function
                 ):
        store_attr()
        self.__doc__ = f"Convert '{col_src}' column values to lowercase, strip spaces, and store in '{col_dst}' column."
        if not col_dst: self.col_dst = col_src
        
    def _safe_transform(self, value):
        "Ensure value is not NA and apply transformation function."
        return value if pd.isna(value) else self.fn_transform(str(value))

    def each_grp(self, grp, df, tfm): df[self.col_dst] = df[self.col_src].apply(self._safe_transform)

# %% ../nbs/api/callbacks.ipynb #949d6471
class AddSampleTypeIdColumnCB(PerGroupCB):
    "Add a column with the sample type as defined in the CDL."
    def __init__(self, 
                 lut: dict=SMP_TYPE_LUT, # Lookup table for sample type
                 col_name: str='SAMPLE_TYPE' # Column name to store the sample type id
                 ): 
        store_attr()
        
    def each_grp(self, grp, df, tfm): df[self.col_name] = self.lut[grp]

# %% ../nbs/api/callbacks.ipynb #9da3e703
class RenameColumnsCB(PerGroupCB):
    "Rename variables to MARIS standard names, keeping only renamed columns."
    def __init__(self,
                 renaming_rules: dict # Renaming rules {old_name: new_name}
                 ): 
        store_attr()
        
    def each_grp(self, grp, df, tfm): tfm.dfs[grp] = df[self.renaming_rules.keys()].rename(columns=self.renaming_rules)


# %% ../nbs/api/callbacks.ipynb #2f76c626
class RenameColsCB(PerGroupCB):
    "Rename provider columns to MARIS standard names; optionally cast specified columns to str."
    class Schema(BaseModel):
        mapping:     dict[str, str] = Field(default_factory=dict)
        string_cast: list[str]      = Field(default_factory=list)
    def __init__(self, mapping: dict=None, string_cast: list=None):
        self.cfg = self.Schema(mapping=mapping or {}, string_cast=string_cast or [])
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        df.rename(columns=self.cfg.mapping, inplace=True)
        for col in self.cfg.string_cast:
            df[col] = df[col].astype(str)

# %% ../nbs/api/callbacks.ipynb #1ea2cc64
class RemoveAllNAValuesCB(Callback):
    "Remove rows with all NA values in specified columns."
    def __init__(self, 
                 cols_to_check: Union[Dict[str, list], list],  # Dict or list of columns to check
                 how: str='all'  # How to handle NA values 'all' or 'any'
                ):
        store_attr()

    def __call__(self, tfm):
        # Convert list to dict if cols_to_check is a list
        cols_dict = (self.cols_to_check if isinstance(self.cols_to_check, dict) 
                    else {k: self.cols_to_check for k in tfm.dfs.keys()})
        
        for sample_type, columns in cols_dict.items():
            tfm.dfs[sample_type].dropna(
                subset=columns,
                how=self.how,
                inplace=True
            )

# %% ../nbs/api/callbacks.ipynb #d7982397
class MeltWideNuclidesCB(Callback):
    "Reshape wide nuclide columns to long format using a named-dict spec."
    def __init__(self,
                 spec: list,           # List of dicts with keys: val, unc, nuclide, unit, lab
                 grp:  str='SEAWATER', # Group in tfm.dfs to reshape
                 ):
        store_attr()

    def __call__(self, tfm):
        if self.grp not in tfm.dfs: return
        df = tfm.dfs[self.grp]
        frames = []
        for s in self.spec:
            sub = df.dropna(subset=[s['val']]).copy()
            sub['NUCLIDE'] = s['nuclide']
            sub['VALUE']   = sub[s['val']]
            sub['UNC']     = sub[s['unc']]
            sub['UNIT']    = s['unit']
            sub['LAB']     = s['lab']
            frames.append(sub)
        if frames:
            tfm.dfs[self.grp] = pd.concat(frames, ignore_index=True)

# %% ../nbs/api/callbacks.ipynb #38a49c42
class SoftMeltWideNuclidesCB(PerGroupCB):
    "Reshape wide nuclide columns to long format; spec=None/[] is a safe Null-Object no-op."
    class Schema(BaseModel):
        spec: list = Field(default_factory=list)

    def __init__(self, spec: list=None, grp: str='SEAWATER'):
        self.cfg  = self.Schema(spec=spec or [])
        self.grps = [grp]

    def each_grp(self, grp, df, tfm):
        frames = []
        for s in self.cfg.spec:
            sub = df.dropna(subset=[s['val']]).copy()
            sub['NUCLIDE'] = s['nuclide']
            sub['VALUE']   = sub[s['val']]
            sub['UNC']     = sub[s['unc']]
            sub['UNIT']    = s['unit']
            sub['LAB']     = s['lab']
            frames.append(sub)
        tfm.dfs[grp] = pd.concat(frames or [df], ignore_index=True)

# %% ../nbs/api/callbacks.ipynb #7bb09e18
class AddSampleIDCB(PerGroupCB):
    "Assign 1-based sequential SMP_ID; optionally cast a provider ID column to str for NetCDF VLEN compatibility."
    def __init__(self,
                 col_provider: str=None,  # Provider ID column to cast to str; None = skip
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.reset_index(drop=True)
        tfm.dfs[grp]['SMP_ID'] = tfm.dfs[grp].index + 1
        if self.col_provider:
            tfm.dfs[grp][self.col_provider] = tfm.dfs[grp][self.col_provider].astype(str).astype(object)

# %% ../nbs/api/callbacks.ipynb #8cf07327
class CompareDfsAndTfmCB(Callback):
    "Create a dataframe of removed data and track changes in row counts due to transformations."  # TODO: refactor - too long
    def __init__(self, 
                 dfs: Dict[str, pd.DataFrame]  # Original dataframes
                 ): 
        store_attr()
        
    def __call__(self, tfm: Transformer) -> None:
        self._initialize_tfm_attributes(tfm)
        for grp in tfm.dfs.keys():
            self._compute_changes(grp, tfm)

    def _initialize_tfm_attributes(self, tfm: Transformer) -> None:
        tfm.dfs_removed = {}
        tfm.compare_stats = {}

    def _compute_changes(self, 
                         grp: str,  # The group key
                         tfm: Transformer  # The transformation object containing `dfs`
                        ) -> None:
        "Compute and store changes including data removed and created during transformation."
        original_df = self.dfs[grp]
        transformed_df = tfm.dfs[grp]

        # Calculate differences
        original_count = len(original_df.index)
        transformed_count = len(transformed_df.index)
        removed_count = len(original_df.index.difference(transformed_df.index))
        created_count = len(transformed_df.index.difference(original_df.index))

        # Store results
        tfm.dfs_removed[grp] = original_df.loc[original_df.index.difference(transformed_df.index)]
        tfm.compare_stats[grp] = {
            'Original row count (dfs)': original_count,
            'Transformed row count (tfm.dfs)': transformed_count,
            'Rows removed from original (tfm.dfs_removed)': removed_count,
            'Rows created in transformed (tfm.dfs_created)': created_count
        }

# %% ../nbs/api/callbacks.ipynb #3653a68d
class UniqueIndexCB(PerGroupCB):
    "Set unique index for each group."
    def __init__(self, index_name='ID'): store_attr()
        
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.reset_index(drop=True).reset_index(names=[self.index_name])

# %% ../nbs/api/callbacks.ipynb #c787de45
class ParseTimeCB(PerGroupCB):
    "Parse time column from ISO8601 string to datetime."
    def __init__(self, time_col_name: str='TIME'): store_attr()
    def each_grp(self, grp, df, tfm):
        df[self.time_col_name] = pd.to_datetime(df[self.time_col_name], format='ISO8601')

# %% ../nbs/api/callbacks.ipynb #7f03e81c
class EncodeTimeCB(PerGroupCB):
    "Encode time as seconds since epoch."    
    def __init__(self, 
                   col_time: str='TIME',  # Time column name
                   verbose: bool=False,  # Print warning about missing time values
                   fn_units: Callable=get_time_units # Function returning the time units
                 ): 
        store_attr()
        self.units = fn_units()

    def each_grp(self, grp: str, df: pd.DataFrame, tfm):
        n_missing = df[self.col_time].isna().sum()
        if self.verbose and n_missing: print(f"Warning: {n_missing} missing time value(s) in {grp}")
        tfm.dfs[grp] = df[df[self.col_time].notna()]
        tfm.dfs[grp][self.col_time] = tfm.dfs[grp][self.col_time].apply(lambda x: date2num(x, units=self.units))

# %% ../nbs/api/callbacks.ipynb #41dcef31
class DecodeTimeCB(PerGroupCB):
    "Decode time from seconds since epoch to datetime format."    
    def __init__(self, 
                 col_time: str='TIME',
                 fn_units: Callable=get_time_units # Function returning the time units
                 ): 
        store_attr()
        self.units = fn_units()

    def each_grp(self, grp, df, tfm):
        n_missing = df[self.col_time].isna().sum()
        if n_missing: print(f"Warning: {n_missing} missing time value(s) in {grp}.")
        tfm.dfs[grp] = df[df[self.col_time].notna()]
        tfm.dfs[grp][self.col_time] = tfm.dfs[grp][self.col_time].apply(
            lambda x: num2date(x, units=self.units, only_use_cftime_datetimes=False)
        )

# %% ../nbs/api/callbacks.ipynb #b57fe596
class SoftParseDateTimeCB(PerGroupCB):
    "Parse date and time columns into a UTC-aware TIME column; col_date=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        col_date: Optional[str] = None
        col_time: Optional[str] = None
        fmt: str = "%Y-%m-%d"
    def __init__(self, col_date=None, col_time=None, fmt="%Y-%m-%d"):
        self.cfg  = self.Schema(col_date=col_date, col_time=col_time, fmt=fmt)
        self.grps = None if col_date else [None]
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        date_str = df[self.cfg.col_date].astype(str)
        time_str = df.get(self.cfg.col_time, pd.Series("", index=df.index)).astype(str)
        df['TIME'] = pd.to_datetime((date_str + " " + time_str).str.strip(),
                                    format=self.cfg.fmt, utc=True)

# %% ../nbs/api/callbacks.ipynb #62bb0577
class SoftConvertUnitCB(PerGroupCB):
    "Apply a scalar unit conversion to rows matching a specific nuclide; rule=None is a safe Null-Object no-op."
    class UnitConversionRule(BaseModel):
        nuclide:  str
        src_unit: str
        dst_unit: str
        factor:   float
    def __init__(self, rule: dict = None):
        self.grps = [None] if rule is None else None
        if rule: self.cfg = self.UnitConversionRule(**rule)
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        mask = df['NUCLIDE'] == self.cfg.nuclide
        df.loc[mask, 'VALUE'] *= self.cfg.factor
        df.loc[mask, 'UNC']   *= self.cfg.factor
        df.loc[mask, 'UNIT']   = self.cfg.dst_unit

# %% ../nbs/api/callbacks.ipynb #ac4d6baa
class SoftRelToAbsUncCB(PerGroupCB):
    "Convert relative uncertainty (%) to absolute; col_value=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        col_value:   Optional[str] = None
        col_unc_rel: str           = "UNC_REL"
        factor:      float         = 100.0
    def __init__(self, col_value=None, col_unc_rel="UNC_REL", factor=100.0):
        self.cfg  = self.Schema(col_value=col_value, col_unc_rel=col_unc_rel, factor=factor)
        self.grps = [None] if col_value is None else None
    def each_grp(self, grp, df, tfm):                       # ZERO ast.If
        df["UNC"] = df[self.cfg.col_unc_rel] * df[self.cfg.col_value] / self.cfg.factor


class SoftExtractUnitFromColCB(PerGroupCB):
    "Extract unit string from a column via regex; src_col=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        src_col: Optional[str] = None
        dst_col: str           = "UNIT"
        pattern: str           = r"\((.*?)\)"             # default: parentheses
    def __init__(self, src_col=None, dst_col="UNIT", pattern=r"\((.*?)\)"):
        self.cfg  = self.Schema(src_col=src_col, dst_col=dst_col, pattern=pattern)
        self.grps = [None] if src_col is None else None
    def each_grp(self, grp, df, tfm):                       # ZERO ast.If
        df[self.cfg.dst_col] = df[self.cfg.src_col].str.extract(self.cfg.pattern, expand=False)


class SoftShiftLonCB(PerGroupCB):
    "Shift longitude convention; shift=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        col:   str            = "LON"
        shift: Optional[float] = None
    def __init__(self, col="LON", shift=None):
        self.cfg  = self.Schema(col=col, shift=shift)
        self.grps = [None] if shift is None else None
    def each_grp(self, grp, df, tfm):                       # ZERO ast.If
        df[self.cfg.col] = df[self.cfg.col] - self.cfg.shift


class SoftDMStoDecimalCB(PerGroupCB):
    "Convert degree-minute-second columns to decimal degrees; col_deg=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        col_deg: Optional[str] = None
        col_min: str           = "MIN"
        col_sec: str           = "SEC"
        col_dir: Optional[str] = None
        dst_col: str           = "LAT"
        neg_dir: list          = Field(default_factory=lambda: ["S", "W"])
    def __init__(self, col_deg=None, col_min="MIN", col_sec="SEC",
                 col_dir=None, dst_col="LAT", neg_dir=None):
        self.cfg  = self.Schema(col_deg=col_deg, col_min=col_min, col_sec=col_sec,
                                col_dir=col_dir, dst_col=dst_col,
                                neg_dir=neg_dir or ["S", "W"])
        self.grps = [None] if col_deg is None else None
    def each_grp(self, grp, df, tfm):                       # ZERO ast.If
        decimal = df[self.cfg.col_deg] + df[self.cfg.col_min] / 60 + df[self.cfg.col_sec] / 3600
        df[self.cfg.dst_col] = np.where(df[self.cfg.col_dir].isin(self.cfg.neg_dir),
                                        -decimal, decimal)
