"""Callbacks to populate NetCDF global attributes.

Docs: https://franckalbinet.github.io/mariscoapi/metadata.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/metadata.ipynb.

# %% auto #0
__all__ = ['INIS_QA_API', 'INIS_API', 'DEFAULT_ZENODO_RECORDS_URL', 'DEFAULT_ZENODO_TIMEOUT', 'GlobAttrsFeeder', 'BboxCB',
           'DepthRangeCB', 'TimeRangeCB', 'ZoteroClient', 'ZoteroCB', 'fetch_inis', 'find_curl', 'INISClient', 'InisCB',
           'ZenodoItem', 'ZenodoCB', 'KeyValuePairCB']

# %% ../nbs/api/metadata.ipynb #b4934cd2
import os
import shutil
import subprocess, json
import pandas as pd
from fastcore.all import *
from cftime import num2date
from pyzotero import zotero, zotero_errors
import json
from typing import Dict, List, Callable
from .utils import get_bbox
from .configs import get_time_units, cfg
from .callbacks import run_cbs, Callback

# %% ../nbs/api/metadata.ipynb #6db2b6ee
class GlobAttrsFeeder:
    "Produce NetCDF global attributes as specified by the callbacks."
    def __init__(self, 
                 dfs: Dict[str, pd.DataFrame], # Dictionary of NetCDF group DataFrames
                 cbs: List[Callback]=None, # Callbacks
                 logs: List[str]=None # List of preprocessing steps taken
                 ) -> None:
        store_attr()
        if self.cbs is None: self.cbs = []
        if self.logs is None: self.logs = []
        self.attrs = {}

    def callback(self):
        run_cbs(self.cbs, self)

    def __call__(self):
        self.callback()
        return self.attrs

# %% ../nbs/api/metadata.ipynb #e29022dc
class BboxCB(Callback):
    "Compute dataset geographical bounding box"
    def __call__(self, obj):
        bbox = get_bbox(pd.concat(obj.dfs))     
        lon_min, lon_max, lat_min, lat_max = [str(bound) for bound in bbox.bounds]
        obj.attrs.update({
            'geospatial_lat_min': lat_min, 
            'geospatial_lat_max': lat_max,
            'geospatial_lon_min': lon_min,
            'geospatial_lon_max': lon_max,
            'geospatial_bounds': bbox.wkt})

# %% ../nbs/api/metadata.ipynb #813cbfe2
class DepthRangeCB(Callback):
    "Compute minimum and maximum depth values"
    def __init__(self, 
                 depth_col: str='SMP_DEPTH' # Column name for sampling depth values
                ): 
        store_attr()
    def __call__(self, obj):
        depths = pd.concat(obj.dfs).get(self.depth_col, default=pd.Series([]))
        if not depths.empty:
            obj.attrs.update({
                'geospatial_vertical_max': str(depths.max()),
                'geospatial_vertical_min': str(depths.min())})

# %% ../nbs/api/metadata.ipynb #d12b933c
class TimeRangeCB(Callback):
    "Compute time coverage start and end dates"
    def __init__(self, 
                 time_col: str='TIME',         # Column name for time values
                 fn_time_unit: Callable=get_time_units  # Function returning the NetCDF time unit string
                ): 
        store_attr()
        self.time_unit = fn_time_unit()
    
    def __call__(self, obj):
        time = pd.concat(obj.dfs)[self.time_col]
        start, end = [num2date(t, units=self.time_unit).isoformat() 
                      for t in (time.min(), time.max())]
        obj.attrs.update({
            'time_coverage_start': start,
            'time_coverage_end': end})

# %% ../nbs/api/metadata.ipynb #761032af
class ZoteroClient:
    "Zotero API client to fetch a bibliographic record."
    def __init__(self, 
                 item_id: str, # Zotero item key to retrieve
                 lib_id: str,  # Zotero library ID
                 api_key: str  # Zotero API key
                ) -> None:
        store_attr()
        try: self.item = self.get_item(item_id)
        except Exception: self.item = None
    
    def exist(self) -> bool: return self.item is not None
    
    def get_item(self, item_id:str  # Zotero item key to retrieve
               ) -> dict|None:      # Zotero item dict, or None if not found
        zot = zotero.Zotero(self.lib_id, 'group', self.api_key)
        try:
            return zot.item(item_id)
        except zotero_errors.ResourceNotFoundError:
            print(f'Item {item_id} does not exist in Zotero library')
            return None
            
    def _get(self, key:str  # Zotero data key to retrieve
            ) -> str:       # Value for that key, or '' if item not loaded
        return self.item['data'][key] if self.item else ''

    @property
    def title(self) -> str: return self._get('title')

    @property
    def summary(self) -> str: return self._get('abstractNote')

    @property
    def creator_name(self) -> str: return json.dumps(self._get('creators'))

    def __repr__(self): return json.dumps(self.item, indent=4)

# %% ../nbs/api/metadata.ipynb #1328e775
class ZoteroCB(Callback):
    "Populate global attributes from Zotero bibliographic metadata."
    def __init__(self, 
                 itemId,   # Zotero item key to retrieve
                ): store_attr()
    def __call__(self, obj):
        c = cfg()['zotero']
        item = ZoteroClient(self.itemId, c['lib_id'], c['api_key'])
        if item.exist(): 
            obj.attrs['id'] = item.item['key']
            for attr in ['title','summary', 'creator_name']:
                obj.attrs[attr] = getattr(item, attr)

# %% ../nbs/api/metadata.ipynb #ac655627
INIS_QA_API = "https://inis-qa.iaea.org/api/records"
INIS_API = "https://inis.iaea.org/api/records"

# %% ../nbs/api/metadata.ipynb #7c30b408
def fetch_inis(
    inis_id:str,   # INIS record identifier (e.g. 'vq0ha-86k24')
    base_url:str=INIS_API # API base URL
    ) -> dict:    # Raw INIS record payload
    "Fetch an INIS record from the InvenioRDM API via curl."
    url = f"{base_url}/{inis_id}"
    r = subprocess.run([find_curl(), '-sS', '-H', 'Accept: application/json', url],
                       capture_output=True, text=True, check=True)
    return json.loads(r.stdout)

# %% ../nbs/api/metadata.ipynb #e578b23a
def find_curl() -> str:
    "Return path to curl, or raise FileNotFoundError."
    path = shutil.which('curl')
    if not path: raise FileNotFoundError(
        "curl not found. Install curl (https://curl.se) — it's required to fetch INIS records.")
    return path

# %% ../nbs/api/metadata.ipynb #ac02991e
class INISClient:
    "Retrieve INIS metadata from the InvenioRDM API."
    def __init__(self,
                 inis_id:str,   # INIS record identifier (e.g. 'vq0ha-86k24')
                 base_url:str=INIS_API # API base URL
                 ) -> None:
        store_attr()
        try: self.item = fetch_inis(inis_id, base_url)
        except Exception: self.item = None

    def exist(self) -> bool:
        "Does the record exist? The API returns {'status': 404, ...} (not an HTTP 404) for missing IDs, so check for a top-level 'id' key rather than relying on an exception."
        return self.item is not None and 'id' in self.item

    @property
    def title(self) -> str:
        if not self.item: return ''
        t = self.item.get('metadata', {}).get('title', '') or ''
        if isinstance(t, str): return t
        return t.get('en') or next((v for v in t.values() if v), '')

    @property
    def summary(self) -> str:
        if not self.item: return ''
        d = self.item.get('metadata', {}).get('description', '') or ''
        if isinstance(d, str): return d
        return d.get('en') or next((v for v in d.values() if v), '')

    @property
    def doi(self) -> str:
        if not self.item: return ''
        doi = self.item.get('pids', {}).get('doi', {})
        if isinstance(doi, dict): doi = doi.get('identifier') or ''
        if doi: return doi
        for ident in self.item.get('metadata', {}).get('identifiers', []):
            if ident.get('scheme') == 'doi': return ident.get('identifier', '')
        return ''

    @property
    def creator_name(self) -> str:
        if not self.item: return ''
        return json.dumps(self.item.get('metadata', {}).get('creators', []), ensure_ascii=True)

    @property
    def url(self) -> str:
        if not self.item: return ''
        links = self.item.get('links', {})
        return links.get('self_html') or links.get('latest_html') or links.get('self', '')

# %% ../nbs/api/metadata.ipynb #fd6f5646
class InisCB(Callback):
    "Populate global attributes from INIS metadata."
    def __init__(self,
                 inis_id:str, # INIS record identifier to retrieve
                 base_url:str=INIS_API # API base URL
                ): store_attr()
    def __call__(self, obj):
        item = INISClient(self.inis_id, self.base_url)
        if item.exist():
            obj.attrs['id'] = self.inis_id
            for attr in ['title', 'summary', 'creator_name']:
                obj.attrs[attr] = getattr(item, attr)
            if item.doi: obj.attrs['references'] = item.doi
            if item.url: obj.attrs['metadata_link'] = item.url

# %% ../nbs/api/metadata.ipynb #zenodo-constants
import httpx
from urllib.parse import urlencode

# Stable single-record retrieval endpoint; TITANICA community discovery stays upstream.
DEFAULT_ZENODO_RECORDS_URL = 'https://zenodo.org/api/records'
DEFAULT_ZENODO_TIMEOUT = 10.0

class _ZenodoMetadataError(Exception):
    "Raised when Zenodo metadata retrieval fails."
    pass

class _ZenodoMissingRecordError(_ZenodoMetadataError):
    "Raised when the selected Zenodo record does not exist."
    pass

class _ZenodoTransportError(_ZenodoMetadataError):
    "Raised when Zenodo transport fails before a valid payload is received."
    pass

# %% ../nbs/api/metadata.ipynb #zenodo-transport
def _zenodo_build_client(timeout:float=DEFAULT_ZENODO_TIMEOUT):
    return httpx.Client(
        timeout=timeout,
        headers={'Accept': 'application/json'},
        limits=httpx.Limits(max_keepalive_connections=5, max_connections=10),
    )

def _zenodo_find_curl() -> str:
    path = shutil.which('curl') or shutil.which('curl.exe')
    if not path: raise _ZenodoTransportError('Zenodo metadata retrieval failed: curl not found')
    return path

def _zenodo_httpx_json(client, url:str, params:dict=None):
    try:
        response = client.get(url, params=params)
        response.raise_for_status()
        return response.json()
    except httpx.HTTPStatusError as exc:
        status_code = exc.response.status_code if exc.response else 'unknown'
        if status_code == 404: raise _ZenodoMissingRecordError('Zenodo metadata retrieval failed: record not found') from exc
        raise _ZenodoMetadataError(f'Zenodo metadata retrieval failed: HTTP {status_code}') from exc
    except (httpx.RequestError, TimeoutError) as exc:
        raise _ZenodoTransportError(f'Zenodo metadata retrieval failed: {exc}') from exc
    except ValueError as exc:
        raise _ZenodoMetadataError('Zenodo metadata retrieval failed: invalid JSON payload') from exc

def _zenodo_curl_json(url:str, timeout:float=DEFAULT_ZENODO_TIMEOUT, params:dict=None):
    if params: url = f"{url}?{urlencode(params, doseq=True)}"
    try:
        response = subprocess.run(
            [_zenodo_find_curl(), '-sS', '-H', 'Accept: application/json', '-w', r'\n%{http_code}', url],
            capture_output=True, text=True, encoding='utf-8', check=True,
            timeout=max(1, int(timeout * 4)),
        )
        body, _, status_line = response.stdout.rstrip('\n').rpartition('\n')
        status_code = int(status_line)
        if status_code == 404: raise _ZenodoMissingRecordError('Zenodo metadata retrieval failed: record not found')
        if status_code >= 400: raise _ZenodoMetadataError(f'Zenodo metadata retrieval failed: HTTP {status_code}')
        return json.loads(body)
    except subprocess.TimeoutExpired as exc:
        raise _ZenodoTransportError(f'Zenodo metadata retrieval failed: {exc}') from exc
    except subprocess.CalledProcessError as exc:
        raise _ZenodoMetadataError('Zenodo metadata retrieval failed: curl returned a non-zero exit code') from exc
    except ValueError as exc:
        raise _ZenodoMetadataError('Zenodo metadata retrieval failed: invalid curl response payload') from exc

def _zenodo_fetch_json(url:str, timeout:float=DEFAULT_ZENODO_TIMEOUT, params:dict=None, client=None):
    if client is not None: return _zenodo_httpx_json(client, url, params=params)
    httpx_client = _zenodo_build_client(timeout)
    try: return _zenodo_httpx_json(httpx_client, url, params=params)
    except _ZenodoTransportError: return _zenodo_curl_json(url, timeout=timeout, params=params)
    finally: httpx_client.close()

def _zenodo_fetch_record(record_id:str,
                         record_base_url:str=DEFAULT_ZENODO_RECORDS_URL,
                         timeout:float=DEFAULT_ZENODO_TIMEOUT, client=None):
    url = f"{record_base_url.rstrip('/')}/{record_id}"
    return _zenodo_fetch_json(url, timeout=timeout, client=client)

# %% ../nbs/api/metadata.ipynb #zenodo-shape-helpers
def _zenodo_as_dict(value): return value if isinstance(value, dict) else {}
def _zenodo_as_list(value): return value if isinstance(value, list) else []
def _zenodo_pick_text(value):
    if isinstance(value, str): return value
    if isinstance(value, dict):
        if value.get('en'): return value.get('en')
        return next((v for v in value.values() if isinstance(v, str) and v), '')
    return '' if value is None else str(value)

# %% ../nbs/api/metadata.ipynb #zenodo-parse-helpers
def _zenodo_normalize_creator(creator):
    creator = _zenodo_as_dict(creator)
    person = _zenodo_as_dict(creator.get('person_or_org'))
    name = _zenodo_pick_text(creator.get('name')) or _zenodo_pick_text(person.get('name'))
    affiliation = _zenodo_pick_text(creator.get('affiliation')) or _zenodo_pick_text(person.get('affiliation'))
    orcid = _zenodo_pick_text(creator.get('orcid'))
    if not orcid:
        identifiers = _zenodo_as_list(creator.get('identifiers')) or _zenodo_as_list(person.get('identifiers'))
        for ident in identifiers:
            ident = _zenodo_as_dict(ident)
            if _zenodo_pick_text(ident.get('scheme')).lower() == 'orcid':
                orcid = _zenodo_pick_text(ident.get('identifier'))
                break
    cleaned = {}
    if name: cleaned['name'] = name
    if affiliation: cleaned['affiliation'] = affiliation
    if orcid: cleaned['orcid'] = orcid
    return cleaned or None

def _zenodo_creator_name(creators):
    names, seen = [], set()
    for creator in _zenodo_as_list(creators):
        normalized = _zenodo_normalize_creator(creator)
        if not normalized: continue
        key = tuple(sorted(normalized.items()))
        if key in seen: continue
        seen.add(key)
        names.append(normalized)
    return json.dumps(names, ensure_ascii=True)

def _zenodo_doi(record, metadata):
    doi = _zenodo_pick_text(record.get('doi')) or _zenodo_pick_text(metadata.get('doi'))
    if doi: return doi
    pids = _zenodo_as_dict(record.get('pids'))
    return _zenodo_pick_text(_zenodo_as_dict(pids.get('doi')).get('identifier'))

def _zenodo_url(record):
    links = _zenodo_as_dict(record.get('links'))
    return (_zenodo_pick_text(links.get('self_html'))
            or _zenodo_pick_text(links.get('latest_html'))
            or _zenodo_pick_text(record.get('doi_url')))

# %% ../nbs/api/metadata.ipynb #zenodo-item
class ZenodoItem:
    "Retrieve and normalize a selected TITANICA-linked Zenodo record through the stable single-record endpoint."
    def __init__(self,
                 record_id:str, # Zenodo record id that upstream already confirmed belongs to the TITANICA community
                 record_base_url:str=DEFAULT_ZENODO_RECORDS_URL, # Stable single-record retrieval endpoint
                 timeout:float=DEFAULT_ZENODO_TIMEOUT # Request timeout in seconds
                ):
        store_attr()
        try: self.item = _zenodo_fetch_record(self.record_id, self.record_base_url, self.timeout)
        except _ZenodoMissingRecordError: self.item = None

    def exist(self): return self.item is not None and bool(_zenodo_pick_text(_zenodo_as_dict(self.item).get('id')))

    @property
    def id(self) -> str:
        return _zenodo_pick_text(_zenodo_as_dict(self.item).get('id')) if self.item else ''

    @property
    def title(self) -> str:
        metadata = _zenodo_as_dict(_zenodo_as_dict(self.item).get('metadata'))
        return _zenodo_pick_text(metadata.get('title')) if self.item else ''

    @property
    def summary(self) -> str:
        metadata = _zenodo_as_dict(_zenodo_as_dict(self.item).get('metadata'))
        return _zenodo_pick_text(metadata.get('description')) if self.item else ''

    @property
    def creator_name(self) -> str:
        metadata = _zenodo_as_dict(_zenodo_as_dict(self.item).get('metadata'))
        return _zenodo_creator_name(metadata.get('creators', [])) if self.item else '[]'

    @property
    def doi(self) -> str:
        metadata = _zenodo_as_dict(_zenodo_as_dict(self.item).get('metadata'))
        return _zenodo_doi(_zenodo_as_dict(self.item), metadata) if self.item else ''

    @property
    def url(self) -> str:
        return _zenodo_url(_zenodo_as_dict(self.item)) if self.item else ''

    def __repr__(self): return json.dumps(self.item, indent=4)

# %% ../nbs/api/metadata.ipynb #zenodo-callback
class ZenodoCB(Callback):
    "Project a selected TITANICA-linked Zenodo record into NetCDF global attrs without doing discovery or community validation."
    def __init__(self,
                 record_id:str, # Zenodo record id that upstream already confirmed belongs to the TITANICA community
                 record_base_url:str=DEFAULT_ZENODO_RECORDS_URL, # Stable single-record retrieval endpoint
                 timeout:float=DEFAULT_ZENODO_TIMEOUT # Request timeout in seconds
                ): store_attr()
    def __call__(self, obj):
        item = ZenodoItem(self.record_id, record_base_url=self.record_base_url, timeout=self.timeout)
        if item.exist():
            obj.attrs['id'] = self.record_id
            for attr in ['title', 'summary', 'creator_name']: obj.attrs[attr] = getattr(item, attr)
            if item.doi: obj.attrs['references'] = item.doi
            if item.url: obj.attrs['metadata_link'] = item.url

# %% ../nbs/api/metadata.ipynb #daff6f7e
class KeyValuePairCB(Callback):
    "Add a single key-value pair as a NetCDF global attribute."
    def __init__(self, 
                 k, # NetCDF global attribute key name
                 v  # NetCDF global attribute value
                ): store_attr()
    def __call__(self, obj): obj.attrs[self.k] = self.v
