# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/cli/export.ipynb.

# %% auto #0
__all__ = ['main']

# %% ../../nbs/cli/export.ipynb #5ac66ee5
from fastcore.script import *
from pathlib import Path
from ..nc2csv import to_csv

# %% ../../nbs/cli/export.ipynb #fb4d2c30
@call_parse
def main(
    src: str,  # Path to the MARIS NetCDF4 file to convert
    dest: str = None,  # Output path stem for the CSV files (defaults to src stem)
) -> None:
    "Convert a MARIS NetCDF4 file to import-ready CSV files (one per sample type)."
    print(f'Decoding: {Path(src).name} ...')
    to_csv(fname_in=src, dest_out=dest)
