# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/cli/verify.ipynb.

# %% auto #0
__all__ = ['main']

# %% ../../nbs/cli/verify.ipynb #imports
from fastcore.script import *
from pathlib import Path
from marisco.handlers.general import verify

# %% ../../nbs/cli/verify.ipynb #main
@call_parse
def main(
    yaml_path: str,  # Path to the YAML handler contract to verify
) -> None:
    "Dry-run a marisco 3.0 YAML contract through declarative transforms and deep Gate 2 without writing NetCDF."
    verify(Path(yaml_path))
