# marisco/callbacks/__init__.py
# Hand-written backward-compat facade — NOT managed by nbdev.
# Python prefers this package over the sibling callbacks.py (dead, regenerated by nbdev from callbacks.ipynb).
#
# PR-A: shared imports are commented out until shared.py is exported (PR-B).
# PR-B: uncomment `from .shared import ...` block and __all__ shared entries.
# PR-C: uncomment `_GuardedEncodeTimeCB`, `_GuardedSanitizeLonLatCB`.

from .core import (
    Callback, PerGroupCB, run_cbs, Transformer,
    SanitizeLonLatCB, RemapCB, SoftRemapCB,
    RenameColsCB, SoftMeltWideNuclidesCB, AddSampleIDCB,
    EncodeTimeCB, DecodeTimeCB, SoftParseDateTimeCB, SoftConvertUnitCB,
    # Legacy:
    AddSampleTypeIdColumnCB, RenameColumnsCB, RemoveAllNAValuesCB,
    MeltWideNuclidesCB, CompareDfsAndTfmCB, UniqueIndexCB, ParseTimeCB,
    # PR-C: Topology Guards promoted from general.py inner classes
    _GuardedEncodeTimeCB, _GuardedSanitizeLonLatCB,
)

# PR-B: shared.ipynb exported -> uncomment activated
from .shared import (
    LowerStripNameCB,
    SoftRelToAbsUncCB, SoftExtractUnitFromColCB,
    SoftShiftLonCB, SoftDMStoDecimalCB,
    SoftAssetRemapCB, SoftRegexTransformCB,
)

__all__ = [
    # Core
    'Callback', 'PerGroupCB', 'run_cbs', 'Transformer',
    'SanitizeLonLatCB', 'RemapCB', 'SoftRemapCB',
    'RenameColsCB', 'SoftMeltWideNuclidesCB', 'AddSampleIDCB',
    'EncodeTimeCB', 'DecodeTimeCB', 'SoftParseDateTimeCB', 'SoftConvertUnitCB',
    # Legacy
    'AddSampleTypeIdColumnCB', 'RenameColumnsCB', 'RemoveAllNAValuesCB',
    'MeltWideNuclidesCB', 'CompareDfsAndTfmCB', 'UniqueIndexCB', 'ParseTimeCB',
    # PR-C: Topology Guards
    '_GuardedEncodeTimeCB', '_GuardedSanitizeLonLatCB',
    # Shared
    'LowerStripNameCB',
    'SoftRelToAbsUncCB', 'SoftExtractUnitFromColCB',
    'SoftShiftLonCB', 'SoftDMStoDecimalCB',
    'SoftAssetRemapCB', 'SoftRegexTransformCB',
]
