"""Platform infra + standard 11-rail CBs + topology guards.
Auto-generated by nbdev from `nbs/api/callbacks/core.ipynb`.

Docs: https://franckalbinet.github.io/mariscoapi/callbacks/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/callbacks/core.ipynb.

# %% ../../nbs/api/callbacks/core.ipynb #5a293345
from __future__ import annotations
import copy
from functools import singledispatch
from fastcore.all import *
from operator import attrgetter
from cftime import date2num ,num2date
import numpy as np
import pandas as pd
from typing import List, Dict, Callable, Any, Optional, Union, ClassVar
from collections import defaultdict
from ..configs import get_lut, get_time_units, NC_GROUPS, SMP_TYPE_LUT
from pydantic import BaseModel, Field, ConfigDict


# %% auto #0
__all__ = ['Callback', 'PerGroupCB', 'run_cbs', 'PipelineState', 'run_pipeline', 'Transformer', 'SanitizeLonLatCB', 'RemapCB',
           'SoftRemapCB', 'RenameColsCB', 'SoftMeltWideNuclidesCB', 'AddSampleIDCB', 'EncodeTimeCB', 'DecodeTimeCB',
           'SoftParseDateTimeCB', 'SoftConvertUnitCB']

# %% ../../nbs/api/callbacks/core.ipynb #4e58c73c
class Callback(): 
    "Base class for callbacks."
    order = 0
    def __init__(self): pass

# %% ../../nbs/api/callbacks/core.ipynb #0414ac1d
class PerGroupCB(Callback):
    "Calls `each_grp` for each group in `state.dfs`; set `grps` to restrict to specific groups."
    grps: list = None

    def __init__(self,
                 grps: list=None  # Groups to process; None = all groups in `state.dfs`
                 ):
        if grps is not None: self.grps = grps

    def __call__(self, state: PipelineState):
        for grp in (self.grps or state.dfs):
            if grp in state.dfs: self.each_grp(grp, state.dfs[grp], state)

# %% ../../nbs/api/callbacks/core.ipynb #92cf2c26
@patch
def each_grp(self:PerGroupCB,
             grp: str,                    # Group key e.g. `'SEAWATER'`, `'BIOTA'`
             df: pd.DataFrame,            # DataFrame for this group
             state: PipelineState,        # Pipeline state carrying dfs + logs
             ):
    "Override to implement per-group transformation logic."
    raise NotImplementedError

# %% ../../nbs/api/callbacks/core.ipynb #61702d17
def run_cbs(
    cbs: List[Callback], # List of callbacks to run
    obj: Any # Object to pass to the callbacks
    ):
    "Run the callbacks in the order they are specified."
    for cb in sorted(cbs, key=attrgetter('order')):
        if cb.__doc__: obj.logs.append(cb.__doc__)
        cb(obj)

# %% ../../nbs/api/callbacks/core.ipynb #82a6611d
# ── Type-dispatch table: ZERO isinstance inside Transformer body ──────────────
@singledispatch
def _dfs_from(data: Any, inplace: bool, key: str) -> Dict[str, pd.DataFrame]:
    "Fallback: raise on unsupported data type."
    raise TypeError(f"Unsupported Transformer data type: {type(data)!r}")

@_dfs_from.register(pd.DataFrame)
def _(data: pd.DataFrame, inplace: bool, key: str) -> Dict[str, pd.DataFrame]:
    return {key: data if inplace else data.copy()}

@_dfs_from.register(dict)
def _(data: dict, inplace: bool, key: str) -> Dict[str, pd.DataFrame]:
    return data if inplace else {k: v.copy() for k, v in data.items()}


class PipelineState(BaseModel):
    "Pure data vessel: dfs + logs + custom_maps. No execution logic."
    model_config = ConfigDict(arbitrary_types_allowed=True, validate_assignment=True)

    _SINGLE_KEY: ClassVar[str] = ""

    dfs:         Dict[str, pd.DataFrame] = Field(default_factory=dict)
    logs:        List[str]               = Field(default_factory=list)
    custom_maps: Any = Field(default_factory=lambda: defaultdict(lambda: defaultdict(dict)))

    @property
    def is_single_df(self) -> bool:
        return self._SINGLE_KEY in self.dfs and len(self.dfs) == 1

    @property
    def df(self) -> Optional[pd.DataFrame]:
        return self.dfs.get(self._SINGLE_KEY)

    def __setattr__(self, name: str, value: Any) -> None:
        if name == 'df':
            if self._SINGLE_KEY not in self.dfs and len(self.dfs) > 0:
                raise ValueError(
                    "Cannot assign state.df in multi-group state "
                    "(active groups: " + str(list(self.dfs.keys())) + "). "
                    "Use state.dfs[grp] instead."
                )
            self.dfs[self._SINGLE_KEY] = value
        else:
            super().__setattr__(name, value)


def run_pipeline(
    state: 'PipelineState',  # Pipeline state (dfs + logs)
    cbs:   List[Callback],    # Callbacks to execute
    ) -> None:
    "Execute callbacks on state in-place; logs accumulated in state.logs."
    run_cbs(cbs, state)


class Transformer:
    "Backward-compatible proxy: wraps PipelineState + cbs. data/inplace are transient."
    _SINGLE_KEY: ClassVar[str] = ""

    def __init__(self,
                 data:        Union[Dict[str, pd.DataFrame], pd.DataFrame],
                 cbs:         Optional[List[Any]] = None,
                 custom_maps: Dict = None,
                 inplace:     bool = False,
                 **kwargs):
        # object.__setattr__ bypasses our __setattr__ guard during init
        object.__setattr__(self, '_state', PipelineState(
            dfs=_dfs_from(data, inplace, Transformer._SINGLE_KEY),
            custom_maps=custom_maps or defaultdict(lambda: defaultdict(dict))
        ))
        object.__setattr__(self, '_cbs', cbs or [])

    @property
    def dfs(self) -> Dict[str, pd.DataFrame]: return self._state.dfs
    @dfs.setter
    def dfs(self, value: Dict) -> None: self._state.dfs = value

    @property
    def df(self) -> Optional[pd.DataFrame]: return self._state.df

    @property
    def logs(self) -> List[str]: return self._state.logs

    @property
    def custom_maps(self) -> Any: return self._state.custom_maps

    @property
    def is_single_df(self) -> bool: return self._state.is_single_df

    def __setattr__(self, name: str, value: Any) -> None:
        if name == 'df':
            self._state.df = value  # delegates to PipelineState state-guard
        else:
            object.__setattr__(self, name, value)

    def __call__(self):
        "Execute pipeline: run cbs on state, return processed data."
        run_pipeline(self._state, self._cbs)
        return (self._state.dfs[self._SINGLE_KEY]
                if self._state.is_single_df else self._state.dfs)


# %% ../../nbs/api/callbacks/core.ipynb #097d66b6
class SanitizeLonLatCB(PerGroupCB):
    "Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator."
    def __init__(self, 
                 lon_col: str='LON', # Longitude column name
                 lat_col: str='LAT', # Latitude column name
                 verbose: bool=False # Whether to print the number of invalid longitude & latitude values
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        df[self.lon_col] = df[self.lon_col].apply(lambda x: float(str(x).replace(',', '.')))
        df[self.lat_col] = df[self.lat_col].apply(lambda x: float(str(x).replace(',', '.')))
        mask_zeroes = (df[self.lon_col] == 0) & (df[self.lat_col] == 0)
        if mask_zeroes.sum() and self.verbose:
            print(f'The "{grp}" group contains {mask_zeroes.sum()} data points whose ({self.lon_col}, {self.lat_col}) = (0, 0)')
        mask_goob = (df[self.lon_col] < -180) | (df[self.lon_col] > 180) | (df[self.lat_col] < -90) | (df[self.lat_col] > 90)
        if mask_goob.sum() and self.verbose:
            print(f'The "{grp}" group contains {mask_goob.sum()} data points with unrealistic {self.lon_col} or {self.lat_col} values.')
        tfm.dfs[grp] = df.loc[~(mask_zeroes | mask_goob)]

# %% ../../nbs/api/callbacks/core.ipynb #8c905654
class RemapCB(PerGroupCB):
    "Remap source values to MARIS standard identifiers using a lookup table."
    def __init__(self,
                 lut: dict|Callable,  # Lookup: dict, or callable(dfs)->dict
                 col_remap: str,            # Destination column to create
                 col_src: str,              # Source column with provider values
                 default_val: int=0,        # Value assigned to unmapped source values
                 grps: list[str]=None,      # Groups to process (None = all)
                ):
        store_attr()
        grp_str = ', '.join(str(g) for g in grps) if grps else 'all'
        self.__doc__ = f"Remap values from '{col_src}' to '{col_remap}' for groups: {grp_str}."

    def _resolve_lut(self, tfm):
        "Resolve the LUT: if a callable, call it with tfm.dfs to produce a dict."
        spec = self.lut
        if callable(spec): spec = spec(tfm.dfs)   # unified dict; single-DF = {"": df}
        return spec

    def __call__(self, tfm):
        self._resolved_lut = self._resolve_lut(tfm)
        super().__call__(tfm)

    def each_grp(self, grp, df, tfm):
        df[self.col_remap] = (df[self.col_src]
            .map(self._resolved_lut).fillna(self.default_val).astype(int))  # grandfathered


# %% ../../nbs/api/callbacks/core.ipynb #30153e7b
class SoftRemapCB(PerGroupCB):
    "Remap source tokens to MARIS IDs; lut=None/empty maps all tokens to default_val (Null-Object no-op)."
    class Schema(BaseModel):
        col_src:    str
        col_remap:  str
        lut:        dict[str, Any] = Field(default_factory=dict)
        default_val: Any           = 0

    def __init__(self,
                 col_src:     str,
                 col_remap:   str,
                 lut:         dict=None,
                 default_val: Any=0,
                 grps: list[str]=None,
                ):
        self.cfg  = self.Schema(col_src=col_src, col_remap=col_remap,
                                lut=lut or {}, default_val=default_val)
        self.grps = [None] if not self.cfg.lut else grps

    def each_grp(self, grp, df, tfm):
        df[self.cfg.col_remap] = (df[self.cfg.col_src]
            .map(self.cfg.lut).fillna(self.cfg.default_val).astype(int))  # grandfathered

# %% ../../nbs/api/callbacks/core.ipynb #2f76c626
class RenameColsCB(PerGroupCB):
    "Rename provider columns to MARIS standard names; optionally cast specified columns to str."
    class Schema(BaseModel):
        mapping:     dict[str, str] = Field(default_factory=dict)
        string_cast: list[str]      = Field(default_factory=list)
    def __init__(self, mapping: dict=None, string_cast: list=None):
        self.cfg = self.Schema(mapping=mapping or {}, string_cast=string_cast or [])
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        df.rename(columns=self.cfg.mapping, inplace=True)
        for col in self.cfg.string_cast:
            df[col] = df[col].astype(str)

# %% ../../nbs/api/callbacks/core.ipynb #38a49c42
class SoftMeltWideNuclidesCB(PerGroupCB):
    "Reshape wide nuclide columns to long format; spec=None/[] is a safe Null-Object no-op."
    class Schema(BaseModel):
        spec: list = Field(default_factory=list)

    def __init__(self, spec: list=None, grp: str='SEAWATER'):
        self.cfg  = self.Schema(spec=spec or [])
        self.grps = [grp]

    def each_grp(self, grp, df, tfm):
        frames = []
        for s in self.cfg.spec:
            sub = df.dropna(subset=[s['val']]).copy()  # grandfathered
            sub['NUCLIDE'] = s['nuclide']
            sub['VALUE']   = sub[s['val']]
            sub['UNC']     = sub[s['unc']]
            sub['UNIT']    = s['unit']
            sub['LAB']     = s['lab']
            frames.append(sub)
        tfm.dfs[grp] = pd.concat(frames or [df], ignore_index=True)

# %% ../../nbs/api/callbacks/core.ipynb #7bb09e18
class AddSampleIDCB(PerGroupCB):
    "Assign 1-based sequential SMP_ID; optionally cast a provider ID column to str for NetCDF VLEN compatibility."
    def __init__(self,
                 col_provider: str=None,  # Provider ID column to cast to str; None = skip
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.reset_index(drop=True)
        tfm.dfs[grp]['SMP_ID'] = tfm.dfs[grp].index + 1
        if self.col_provider:
            tfm.dfs[grp][self.col_provider] = tfm.dfs[grp][self.col_provider].astype(str).astype(object)

# %% ../../nbs/api/callbacks/core.ipynb #7f03e81c
class EncodeTimeCB(PerGroupCB):
    "Encode time as seconds since epoch."    
    def __init__(self, 
                   col_time: str='TIME',  # Time column name
                   verbose: bool=False,  # Print warning about missing time values
                   fn_units: Callable=get_time_units # Function returning the time units
                 ): 
        store_attr()
        self.units = fn_units()

    def each_grp(self, grp: str, df: pd.DataFrame, tfm):
        n_missing = df[self.col_time].isna().sum()
        if self.verbose and n_missing: print(f"Warning: {n_missing} missing time value(s) in {grp}")
        tfm.dfs[grp] = df[df[self.col_time].notna()]
        tfm.dfs[grp][self.col_time] = tfm.dfs[grp][self.col_time].apply(lambda x: date2num(x, units=self.units))

# %% ../../nbs/api/callbacks/core.ipynb #41dcef31
class DecodeTimeCB(PerGroupCB):
    "Decode time from seconds since epoch to datetime format."    
    def __init__(self, 
                 col_time: str='TIME',
                 fn_units: Callable=get_time_units # Function returning the time units
                 ): 
        store_attr()
        self.units = fn_units()

    def each_grp(self, grp, df, tfm):
        n_missing = df[self.col_time].isna().sum()
        if n_missing: print(f"Warning: {n_missing} missing time value(s) in {grp}.")
        tfm.dfs[grp] = df[df[self.col_time].notna()]
        tfm.dfs[grp][self.col_time] = tfm.dfs[grp][self.col_time].apply(
            lambda x: num2date(x, units=self.units, only_use_cftime_datetimes=False)
        )

# %% ../../nbs/api/callbacks/core.ipynb #b57fe596
class SoftParseDateTimeCB(PerGroupCB):
    "Parse date and time columns into a UTC-aware TIME column; col_date=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        col_date: Optional[str] = None
        col_time: Optional[str] = None
        fmt: str = "%Y-%m-%d"
    def __init__(self, col_date=None, col_time=None, fmt="%Y-%m-%d"):
        self.cfg  = self.Schema(col_date=col_date, col_time=col_time, fmt=fmt)
        self.grps = None if col_date else [None]
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        date_str = df[self.cfg.col_date].astype(str)
        time_str = df.get(self.cfg.col_time, pd.Series("", index=df.index)).astype(str)
        df['TIME'] = pd.to_datetime((date_str + " " + time_str).str.strip(),
                                    format=self.cfg.fmt, utc=True)

# %% ../../nbs/api/callbacks/core.ipynb #62bb0577
class SoftConvertUnitCB(PerGroupCB):
    "Apply a scalar unit conversion to rows matching a specific nuclide; rule=None is a safe Null-Object no-op."
    class UnitConversionRule(BaseModel):
        nuclide:  str
        src_unit: str
        dst_unit: str
        factor:   float
    def __init__(self, rule: dict = None):
        self.grps = [None] if rule is None else None
        if rule: self.cfg = self.UnitConversionRule(**rule)
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        mask = df['NUCLIDE'] == self.cfg.nuclide
        df.loc[mask, 'VALUE'] *= self.cfg.factor
        df.loc[mask, 'UNC']   *= self.cfg.factor
        df.loc[mask, 'UNIT']   = self.cfg.dst_unit

# %% ../../nbs/api/callbacks/core.ipynb #guarded_cbs
class _GuardedEncodeTimeCB(EncodeTimeCB):
    "Topology-guarded EncodeTimeCB: auto-degrades to Null-Object (grps=[None]) when TIME absent."
    def __call__(self, tfm):
        self.grps = ([None] if any('TIME' not in df.columns for df in tfm.dfs.values())
                     else None)
        super().__call__(tfm)


class _GuardedSanitizeLonLatCB(SanitizeLonLatCB):
    "Topology-guarded SanitizeLonLatCB: auto-degrades to Null-Object when LON or LAT absent."
    def __call__(self, tfm):
        self.grps = ([None] if any('LON' not in df.columns or 'LAT' not in df.columns
                                   for df in tfm.dfs.values())
                     else None)
        super().__call__(tfm)
