"""Platform infra + standard 11-rail CBs + topology guards.
Auto-generated by nbdev from `nbs/api/callbacks/core.ipynb`.

Docs: https://franckalbinet.github.io/mariscoapi/callbacks/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/callbacks/core.ipynb.

# %% ../../nbs/api/callbacks/core.ipynb #5a293345
from __future__ import annotations
import copy
from fastcore.all import *
from operator import attrgetter
from cftime import date2num ,num2date
import numpy as np
import pandas as pd
from typing import List, Dict, Callable, Any, Optional, Union
from collections import defaultdict
from ..configs import get_lut, get_time_units, NC_GROUPS, SMP_TYPE_LUT
from pydantic import BaseModel, Field

# %% auto #0
__all__ = ['Callback', 'PerGroupCB', 'run_cbs', 'Transformer', 'SanitizeLonLatCB', 'RemapCB', 'SoftRemapCB', 'RenameColsCB',
           'SoftMeltWideNuclidesCB', 'AddSampleIDCB', 'EncodeTimeCB', 'DecodeTimeCB', 'SoftParseDateTimeCB',
           'SoftConvertUnitCB']

# %% ../../nbs/api/callbacks/core.ipynb #4e58c73c
class Callback(): 
    "Base class for callbacks."
    order = 0
    def __init__(self): pass

# %% ../../nbs/api/callbacks/core.ipynb #0414ac1d
class PerGroupCB(Callback):
    "Calls `each_grp` for each group in `tfm.dfs`; set `grps` to restrict to specific groups."
    grps: list = None

    def __init__(self,
                 grps: list=None  # Groups to process; None = all groups in `tfm.dfs`
                 ):
        if grps is not None: self.grps = grps

    def __call__(self, tfm):
        for grp in (self.grps or tfm.dfs):
            if grp in tfm.dfs: self.each_grp(grp, tfm.dfs[grp], tfm)

# %% ../../nbs/api/callbacks/core.ipynb #92cf2c26
@patch
def each_grp(self:PerGroupCB,
             grp: str,          # Group key e.g. `'SEAWATER'`, `'BIOTA'`
             df: pd.DataFrame,  # DataFrame for this group
             tfm,               # Parent `Transformer`
             ):
    "Override to implement per-group transformation logic."
    raise NotImplementedError

# %% ../../nbs/api/callbacks/core.ipynb #61702d17
def run_cbs(
    cbs: List[Callback], # List of callbacks to run
    obj: Any # Object to pass to the callbacks
    ):
    "Run the callbacks in the order they are specified."
    for cb in sorted(cbs, key=attrgetter('order')):
        if cb.__doc__: obj.logs.append(cb.__doc__)
        cb(obj)

# %% ../../nbs/api/callbacks/core.ipynb #82a6611d
class Transformer():
    "Transform the dataframe(s) according to the specified callbacks."
    _SINGLE_KEY = ""  # sentinel key for single-DF mode

    def __init__(self,
                 data: Union[Dict[str, pd.DataFrame], pd.DataFrame],
                 cbs: Optional[List[Callback]]=None,
                 custom_maps: Dict = None,
                 inplace: bool=False
                 ):
        store_attr()
        self.dfs  = self._to_dict(data, inplace)
        self.logs = []
        self.custom_maps = custom_maps or defaultdict(lambda: defaultdict(dict))

    def _to_dict(self, data, inplace) -> Dict[str, pd.DataFrame]:
        "Normalise input to a dict; single DataFrame maps to {_SINGLE_KEY: df}."
        if isinstance(data, pd.DataFrame):
            return {self._SINGLE_KEY: data if inplace else data.copy()}
        return data if inplace else {k: v.copy() for k, v in data.items()}

    @property
    def is_single_df(self) -> bool:
        "True iff sentinel key present AND dict has exactly one entry."
        return self._SINGLE_KEY in self.dfs and len(self.dfs) == 1

    @property
    def df(self) -> Optional[pd.DataFrame]:
        "Single-DF accessor; valid only when constructed with a single DataFrame."
        return self.dfs.get(self._SINGLE_KEY)

    @df.setter
    def df(self, value: pd.DataFrame) -> None:
        "State-contamination guard: raises ValueError in multi-group state."
        if self._SINGLE_KEY not in self.dfs and len(self.dfs) > 0:
            raise ValueError(
                "Cannot assign tfm.df in multi-group state "
                "(active groups: " + str(list(self.dfs.keys())) + "). "
                "Use tfm.dfs[grp] instead."
            )
        self.dfs[self._SINGLE_KEY] = value

    def __call__(self):
        "Transform the dataframe(s) according to the specified callbacks."
        if self.cbs: run_cbs(self.cbs, self)
        return self.dfs[self._SINGLE_KEY] if self.is_single_df else self.dfs


# %% ../../nbs/api/callbacks/core.ipynb #097d66b6
class SanitizeLonLatCB(PerGroupCB):
    "Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator."
    def __init__(self, 
                 lon_col: str='LON', # Longitude column name
                 lat_col: str='LAT', # Latitude column name
                 verbose: bool=False # Whether to print the number of invalid longitude & latitude values
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        df[self.lon_col] = df[self.lon_col].apply(lambda x: float(str(x).replace(',', '.')))
        df[self.lat_col] = df[self.lat_col].apply(lambda x: float(str(x).replace(',', '.')))
        mask_zeroes = (df[self.lon_col] == 0) & (df[self.lat_col] == 0)
        if mask_zeroes.sum() and self.verbose:
            print(f'The "{grp}" group contains {mask_zeroes.sum()} data points whose ({self.lon_col}, {self.lat_col}) = (0, 0)')
        mask_goob = (df[self.lon_col] < -180) | (df[self.lon_col] > 180) | (df[self.lat_col] < -90) | (df[self.lat_col] > 90)
        if mask_goob.sum() and self.verbose:
            print(f'The "{grp}" group contains {mask_goob.sum()} data points with unrealistic {self.lon_col} or {self.lat_col} values.')
        tfm.dfs[grp] = df.loc[~(mask_zeroes | mask_goob)]

# %% ../../nbs/api/callbacks/core.ipynb #8c905654
class RemapCB(PerGroupCB):
    "Remap source values to MARIS standard identifiers using a lookup table."
    def __init__(self,
                 lut: dict|Callable,  # Lookup: dict, or callable(dfs)->dict
                 col_remap: str,            # Destination column to create
                 col_src: str,              # Source column with provider values
                 default_val: int=0,        # Value assigned to unmapped source values
                 grps: list[str]=None,      # Groups to process (None = all)
                ):
        store_attr()
        grp_str = ', '.join(str(g) for g in grps) if grps else 'all'
        self.__doc__ = f"Remap values from '{col_src}' to '{col_remap}' for groups: {grp_str}."

    def _resolve_lut(self, tfm):
        "Resolve the LUT: if a callable, call it with tfm.dfs to produce a dict."
        spec = self.lut
        if callable(spec): spec = spec(tfm.dfs)   # unified dict; single-DF = {"": df}
        return spec

    def __call__(self, tfm):
        self._resolved_lut = self._resolve_lut(tfm)
        super().__call__(tfm)

    def each_grp(self, grp, df, tfm):
        df[self.col_remap] = (df[self.col_src]
            .map(self._resolved_lut).fillna(self.default_val).astype(int))  # grandfathered


# %% ../../nbs/api/callbacks/core.ipynb #30153e7b
class SoftRemapCB(PerGroupCB):
    "Remap source tokens to MARIS IDs; lut=None/empty maps all tokens to default_val (Null-Object no-op)."
    class Schema(BaseModel):
        col_src:    str
        col_remap:  str
        lut:        dict[str, Any] = Field(default_factory=dict)
        default_val: Any           = 0

    def __init__(self,
                 col_src:     str,
                 col_remap:   str,
                 lut:         dict=None,
                 default_val: Any=0,
                 grps: list[str]=None,
                ):
        self.cfg  = self.Schema(col_src=col_src, col_remap=col_remap,
                                lut=lut or {}, default_val=default_val)
        self.grps = [None] if not self.cfg.lut else grps

    def each_grp(self, grp, df, tfm):
        df[self.cfg.col_remap] = (df[self.cfg.col_src]
            .map(self.cfg.lut).fillna(self.cfg.default_val).astype(int))  # grandfathered

# %% ../../nbs/api/callbacks/core.ipynb #2f76c626
class RenameColsCB(PerGroupCB):
    "Rename provider columns to MARIS standard names; optionally cast specified columns to str."
    class Schema(BaseModel):
        mapping:     dict[str, str] = Field(default_factory=dict)
        string_cast: list[str]      = Field(default_factory=list)
    def __init__(self, mapping: dict=None, string_cast: list=None):
        self.cfg = self.Schema(mapping=mapping or {}, string_cast=string_cast or [])
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        df.rename(columns=self.cfg.mapping, inplace=True)
        for col in self.cfg.string_cast:
            df[col] = df[col].astype(str)

# %% ../../nbs/api/callbacks/core.ipynb #38a49c42
class SoftMeltWideNuclidesCB(PerGroupCB):
    "Reshape wide nuclide columns to long format; spec=None/[] is a safe Null-Object no-op."
    class Schema(BaseModel):
        spec: list = Field(default_factory=list)

    def __init__(self, spec: list=None, grp: str='SEAWATER'):
        self.cfg  = self.Schema(spec=spec or [])
        self.grps = [grp]

    def each_grp(self, grp, df, tfm):
        frames = []
        for s in self.cfg.spec:
            sub = df.dropna(subset=[s['val']]).copy()  # grandfathered
            sub['NUCLIDE'] = s['nuclide']
            sub['VALUE']   = sub[s['val']]
            sub['UNC']     = sub[s['unc']]
            sub['UNIT']    = s['unit']
            sub['LAB']     = s['lab']
            frames.append(sub)
        tfm.dfs[grp] = pd.concat(frames or [df], ignore_index=True)

# %% ../../nbs/api/callbacks/core.ipynb #7bb09e18
class AddSampleIDCB(PerGroupCB):
    "Assign 1-based sequential SMP_ID; optionally cast a provider ID column to str for NetCDF VLEN compatibility."
    def __init__(self,
                 col_provider: str=None,  # Provider ID column to cast to str; None = skip
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.reset_index(drop=True)
        tfm.dfs[grp]['SMP_ID'] = tfm.dfs[grp].index + 1
        if self.col_provider:
            tfm.dfs[grp][self.col_provider] = tfm.dfs[grp][self.col_provider].astype(str).astype(object)

# %% ../../nbs/api/callbacks/core.ipynb #7f03e81c
class EncodeTimeCB(PerGroupCB):
    "Encode time as seconds since epoch."    
    def __init__(self, 
                   col_time: str='TIME',  # Time column name
                   verbose: bool=False,  # Print warning about missing time values
                   fn_units: Callable=get_time_units # Function returning the time units
                 ): 
        store_attr()
        self.units = fn_units()

    def each_grp(self, grp: str, df: pd.DataFrame, tfm):
        n_missing = df[self.col_time].isna().sum()
        if self.verbose and n_missing: print(f"Warning: {n_missing} missing time value(s) in {grp}")
        tfm.dfs[grp] = df[df[self.col_time].notna()]
        tfm.dfs[grp][self.col_time] = tfm.dfs[grp][self.col_time].apply(lambda x: date2num(x, units=self.units))

# %% ../../nbs/api/callbacks/core.ipynb #41dcef31
class DecodeTimeCB(PerGroupCB):
    "Decode time from seconds since epoch to datetime format."    
    def __init__(self, 
                 col_time: str='TIME',
                 fn_units: Callable=get_time_units # Function returning the time units
                 ): 
        store_attr()
        self.units = fn_units()

    def each_grp(self, grp, df, tfm):
        n_missing = df[self.col_time].isna().sum()
        if n_missing: print(f"Warning: {n_missing} missing time value(s) in {grp}.")
        tfm.dfs[grp] = df[df[self.col_time].notna()]
        tfm.dfs[grp][self.col_time] = tfm.dfs[grp][self.col_time].apply(
            lambda x: num2date(x, units=self.units, only_use_cftime_datetimes=False)
        )

# %% ../../nbs/api/callbacks/core.ipynb #b57fe596
class SoftParseDateTimeCB(PerGroupCB):
    "Parse date and time columns into a UTC-aware TIME column; col_date=None is a safe Null-Object no-op."
    class Schema(BaseModel):
        col_date: Optional[str] = None
        col_time: Optional[str] = None
        fmt: str = "%Y-%m-%d"
    def __init__(self, col_date=None, col_time=None, fmt="%Y-%m-%d"):
        self.cfg  = self.Schema(col_date=col_date, col_time=col_time, fmt=fmt)
        self.grps = None if col_date else [None]
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        date_str = df[self.cfg.col_date].astype(str)
        time_str = df.get(self.cfg.col_time, pd.Series("", index=df.index)).astype(str)
        df['TIME'] = pd.to_datetime((date_str + " " + time_str).str.strip(),
                                    format=self.cfg.fmt, utc=True)

# %% ../../nbs/api/callbacks/core.ipynb #62bb0577
class SoftConvertUnitCB(PerGroupCB):
    "Apply a scalar unit conversion to rows matching a specific nuclide; rule=None is a safe Null-Object no-op."
    class UnitConversionRule(BaseModel):
        nuclide:  str
        src_unit: str
        dst_unit: str
        factor:   float
    def __init__(self, rule: dict = None):
        self.grps = [None] if rule is None else None
        if rule: self.cfg = self.UnitConversionRule(**rule)
    def each_grp(self, grp, df, tfm):          # ZERO ast.If
        mask = df['NUCLIDE'] == self.cfg.nuclide
        df.loc[mask, 'VALUE'] *= self.cfg.factor
        df.loc[mask, 'UNC']   *= self.cfg.factor
        df.loc[mask, 'UNIT']   = self.cfg.dst_unit

# %% ../../nbs/api/callbacks/core.ipynb #guarded_cbs
class _GuardedEncodeTimeCB(EncodeTimeCB):
    "Topology-guarded EncodeTimeCB: auto-degrades to Null-Object (grps=[None]) when TIME absent."
    def __call__(self, tfm):
        self.grps = ([None] if any('TIME' not in df.columns for df in tfm.dfs.values())
                     else None)
        super().__call__(tfm)


class _GuardedSanitizeLonLatCB(SanitizeLonLatCB):
    "Topology-guarded SanitizeLonLatCB: auto-degrades to Null-Object when LON or LAT absent."
    def __call__(self, tfm):
        self.grps = ([None] if any('LON' not in df.columns or 'LAT' not in df.columns
                                   for df in tfm.dfs.values())
                     else None)
        super().__call__(tfm)
