# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/fram_strait_gen.ipynb.

# %% auto #0
__all__ = ['CSV_URL', 'fname_out', 'ZENODO_ID', 'META_COLS', 'MELT_SPEC', 'U238_PPB_TO_AT_KG', 'NUCLIDE_LUT', 'UNIT_LUT',
           'LAB_NPI', 'LAB_ETH_LIP', 'LAB_LUT', 'AREA_GREENLAND_SEA', 'FRAM_KEYWORDS', 'load_data', 'RenameColsCB',
           'ParseDateTimeCB', 'ConvertU238CB', 'get_attrs', 'encode']

# %% ../../nbs/handlers/fram_strait_gen.ipynb #efb45c90
from fastcore.all import *
import pandas as pd
import numpy as np
import io
import requests

from ..callbacks import (PerGroupCB, Callback, Transformer, EncodeTimeCB,
                                MeltWideNuclidesCB, SanitizeLonLatCB, RemapCB,
                                AddSampleIDCB)
from ..metadata import GlobAttrsFeeder, BboxCB, DepthRangeCB, TimeRangeCB, KeyValuePairCB
from ..encoders import NetCDFEncoder

# %% ../../nbs/handlers/fram_strait_gen.ipynb #9ac28ef3
CSV_URL   = 'https://zenodo.org/records/19387002/files/FramStrait_2020_2021_radionuclides.csv?download=1'
fname_out = 'FramStrait_2020_2021.nc'
ZENODO_ID = '19387002'

# %% ../../nbs/handlers/fram_strait_gen.ipynb #c0d203ba
def load_data(
    url=None  # CSV download URL; defaults to CSV_URL
) -> dict:
    "Fetch Fram Strait radionuclide CSV from Zenodo and return a single SEAWATER DataFrame."
    url = url or CSV_URL
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    return {'SEAWATER': pd.read_csv(io.BytesIO(r.content))}

# %% ../../nbs/handlers/fram_strait_gen.ipynb #87a34eb8
class RenameColsCB(PerGroupCB):
    "Map Fram Strait CTD and sample columns to MARIS standard names."
    grps = ['SEAWATER']
    def each_grp(self, grp, df, tfm):
        df.rename(columns={
            'Latitude_degN': 'LAT', 'Longitude_degE': 'LON',
            'Depth_m': 'SMP_DEPTH', 'Temperature_degC_ctd': 'TEMP',
            'Salinity_ctd': 'SAL', 'Station': 'STATION',
            'Sample_ID': 'SMP_ID_PROVIDER',
        }, inplace=True)
        df['STATION'] = df['STATION'].astype(str)
        df['SMP_ID_PROVIDER'] = df['SMP_ID_PROVIDER'].astype(str)

# %% ../../nbs/handlers/fram_strait_gen.ipynb #e586b695
class ParseDateTimeCB(PerGroupCB):
    "Combine Fram Strait Date and Time columns into a single UTC-aware TIME column."
    grps = ['SEAWATER']
    def __init__(self, col_date='Date',  # Source date column (DD/MM/YYYY)
                 col_time='Time'):       # Source time column (HH:MM:SS)
        store_attr()
    def each_grp(self, grp, df, tfm):
        df['TIME'] = pd.to_datetime(
            df[self.col_date].astype(str) + ' ' + df[self.col_time].astype(str),
            format='%d/%m/%Y %H:%M:%S', utc=True)
        df.drop(columns=[self.col_date, self.col_time], inplace=True)

# %% ../../nbs/handlers/fram_strait_gen.ipynb #56b9b927
# Columns kept as identifiers during the wide-to-long reshape
META_COLS = ['Cruise', 'STATION', 'SMP_ID_PROVIDER', 'LAT', 'LON',
             'TIME', 'SMP_DEPTH', 'TEMP', 'SAL']

# Hand-written spec: each entry maps one value column to its (unc, nuclide, unit, lab).
# NPI uncertainty columns follow unc_{col}; ETH follows ETH_unc_{nuc} — both captured here explicitly.
# U238_ppb is ingested directly with unit='at_ppb'; ConvertU238CB converts to at_kg post-melt.
MELT_SPEC = [
    {'val': 'I129_at_l',      'unc': 'unc_I129_at_l',      'nuclide': 'I129', 'unit': 'at_l',  'lab': 'NPI'},
    {'val': 'I129_at_kg',     'unc': 'unc_I129_at_kg',     'nuclide': 'I129', 'unit': 'at_kg', 'lab': 'NPI'},
    {'val': 'U236_at_l',      'unc': 'unc_U236_at_l',      'nuclide': 'U236', 'unit': 'at_l',  'lab': 'NPI'},
    {'val': 'U236_at_kg',     'unc': 'unc_U236_at_kg',     'nuclide': 'U236', 'unit': 'at_kg', 'lab': 'NPI'},
    {'val': 'U238_ppb',       'unc': 'unc_U238_ppb',       'nuclide': 'U238', 'unit': 'at_ppb','lab': 'NPI'},
    {'val': 'ETH_U236_at_l',  'unc': 'ETH_unc_U236_at_l',  'nuclide': 'U236', 'unit': 'at_l',  'lab': 'ETH'},
    {'val': 'ETH_U236_at_kg', 'unc': 'ETH_unc_U236_at_kg', 'nuclide': 'U236', 'unit': 'at_kg', 'lab': 'ETH'},
]

# %% ../../nbs/handlers/fram_strait_gen.ipynb #bf9464b0
# Convert U-238 from ppb to atoms/kg: ppb * 1e-9 * (1/238.05) * 6.02214076e23
U238_PPB_TO_AT_KG = 2.529_697e12

# %% ../../nbs/handlers/fram_strait_gen.ipynb #13e27a62
class ConvertU238CB(PerGroupCB):
    "Convert U-238 VALUE and UNC from ppb to atoms/kg."
    grps = ['SEAWATER']
    def each_grp(self, grp, df, tfm):
        m = df['NUCLIDE'] == 'U238'
        df.loc[m, 'VALUE'] *= U238_PPB_TO_AT_KG
        df.loc[m, 'UNC']   *= U238_PPB_TO_AT_KG
        df.loc[m, 'UNIT']   = 'at_kg'

# %% ../../nbs/handlers/fram_strait_gen.ipynb #640d35b4
# MARIS nuclide IDs confirmed via dbo_nuclide.xlsx (nc_name column)
NUCLIDE_LUT = {'I129': 28, 'U236': 108, 'U238': 64}

# MARIS unit IDs confirmed via dbo_unit.xlsx (unit_sanitized column)
UNIT_LUT = {'at_kg': 9, 'at_l': 12}

LAB_NPI     = 281   # Norwegian Polar Institute — confirmed via dbo_lab.xlsx
LAB_ETH_LIP = 345   # ETH Zurich / LIP (Casacuberta group) — confirmed via JOIS handler
LAB_LUT     = {'NPI': LAB_NPI, 'ETH': LAB_ETH_LIP}

AREA_GREENLAND_SEA = 2356  # confirmed via dbo_area.xlsx (displayName: 'Greenland Sea')

# %% ../../nbs/handlers/fram_strait_gen.ipynb #1de59911
FRAM_KEYWORDS = ['Fram Strait', 'I-129', 'U-236', 'U-238', 'radionuclides',
                 'seawater', 'Arctic Ocean', 'Norwegian Polar Institute', 'ETH Zurich']

def get_attrs(tfm):
    "Retrieve global attributes for the Fram Strait handler."
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        #InisCB('XXXXXXXX'),  # TODO: add INIS record id when available
        KeyValuePairCB('keywords', ', '.join(FRAM_KEYWORDS)),
        KeyValuePairCB('publisher_postprocess_logs', ', '.join(tfm.logs)),
    ])()

# %% ../../nbs/handlers/fram_strait_gen.ipynb #6a038710
def encode(
    fname_out=None  # Output NetCDF file path; defaults to fname_out
):
    "Encode Fram Strait 2020/2021 data to NetCDF4."
    fname_out = fname_out or globals().get('fname_out', 'FramStrait_2020_2021.nc')
    dfs = load_data()
    tfm = Transformer(dfs, cbs=[
        RenameColsCB(), ParseDateTimeCB(),
        MeltWideNuclidesCB(spec=MELT_SPEC), ConvertU238CB(),
        RemapCB(lut=NUCLIDE_LUT, col_remap='NUCLIDE', col_src='NUCLIDE'),
        RemapCB(lut=UNIT_LUT,    col_remap='UNIT',    col_src='UNIT'),
        RemapCB(lut=LAB_LUT,     col_remap='LAB',     col_src='LAB'),
        RemapCB(lut={}, col_remap='AREA', col_src='NUCLIDE', default_val=AREA_GREENLAND_SEA),
        SanitizeLonLatCB(),
        EncodeTimeCB(),
        AddSampleIDCB(col_provider='SMP_ID_PROVIDER'),
    ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, dest_fname=fname_out, global_attrs=get_attrs(tfm))
    encoder.encode()
