# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/fram_strait2025.ipynb.

# %% auto #0
__all__ = ['RECORDS', 'status', 'FS2025_KEYWORDS', 'load_data', 'RenameColsCB', 'ParseDateTimeCB', 'AddDepthCB', 'AddNuclideCB',
           'AddValueCB', 'AddUnitCB', 'AddUncertCB', 'AddDetectionLimitCB', 'AddLabCB', 'FormatStationCB', 'get_attrs',
           'encode']

# %% ../../nbs/handlers/fram_strait2025.ipynb #d541866d
from fastcore.all import *
import pandas as pd
import numpy as np
import requests
import io
import gsw

from ..callbacks import PerGroupCB, Transformer, EncodeTimeCB, SanitizeLonLatCB, RemapCB, AddSampleIDCB
from ..metadata import GlobAttrsFeeder, BboxCB, DepthRangeCB, TimeRangeCB, KeyValuePairCB
from ..encoders import NetCDFEncoder
from ..nc2csv import to_csv
from ..callbacks import get_lut

# %% ../../nbs/handlers/fram_strait2025.ipynb #585e1b91
RECORDS = {
    "FS2025_i129": {
        "url": "https://zenodo.org/records/20761832/files/FS2025_i129.csv?download=1",
    },
}

status = 'Active'

# %% ../../nbs/handlers/fram_strait2025.ipynb #4f8d0cf6
def load_data() -> dict:
    "Fetch Fram Strait CSV records and return one combined SEAWATER DataFrame"
    parts = []

    for record in RECORDS.values():
        resp = requests.get(record["url"], timeout=60)
        resp.raise_for_status()

        df = pd.read_csv(
            io.BytesIO(resp.content),
            encoding="utf-8-sig",
        )
        parts.append(df)

    return {"SEAWATER": pd.concat(parts, ignore_index=True)}

# %% ../../nbs/handlers/fram_strait2025.ipynb #4a497743
class RenameColsCB(PerGroupCB):
    "Map FS2025 provider columns to MARIS standard names"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.rename(columns={
            "Station": "STATION",
            "Latitude_degN": "LAT",
            "Longitude_degE": "LON",
            "PracticalSalinity": "SAL",
            "Temperature_degC": "TEMP",
            "Sample_ID": "SMP_ID_PROVIDER",
        })

# %% ../../nbs/handlers/fram_strait2025.ipynb #e5342c85
class ParseDateTimeCB(PerGroupCB):
    "Parse FS2025 collection date into a UTC TIME value"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(
            TIME=pd.to_datetime(df["Date"], format="%Y-%m-%d", utc=True)
        ).drop(columns="Date")

# %% ../../nbs/handlers/fram_strait2025.ipynb #72bb4f06
class AddDepthCB(PerGroupCB):
    "Compute sampling depth using Thermodynamic Equation of SeaWater 2010 (TEOS-10)"
    def each_grp(self, grp, df, tfm): 
        df["SMP_DEPTH"] = np.round(-gsw.z_from_p(df['Pressure_dbar'], df['LAT']), 1)

# %% ../../nbs/handlers/fram_strait2025.ipynb #74a889cf
class AddNuclideCB(PerGroupCB):
    "Assign NUCLIDE MARIS ID for I-129"
    def each_grp(self, grp, df, tfm): 
        tfm.dfs[grp] = df.assign(NUCLIDE=28)

# %% ../../nbs/handlers/fram_strait2025.ipynb #84b4ad2a
class AddValueCB(PerGroupCB):
    "Assign VALUE column from the I-129 atoms per litre measurement"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(VALUE=df['I129_at_l'])

# %% ../../nbs/handlers/fram_strait2025.ipynb #b0de014c
class AddUnitCB(PerGroupCB):
    "Assign UNIT MARIS ID for atoms per litre"
    def each_grp(self, grp, df, tfm): 
        tfm.dfs[grp] = df.assign(UNIT=12)

# %% ../../nbs/handlers/fram_strait2025.ipynb #16bc5525
class AddUncertCB(PerGroupCB):
    "Assign UNC column from the I-129 provider uncertainty"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(UNC=df['unc_I129_at_l'])

# %% ../../nbs/handlers/fram_strait2025.ipynb #6fc1506c
class AddDetectionLimitCB(PerGroupCB):
    "Assign missing Detection Limit column to MARIS 'Detected value: 1' category"
    def each_grp(self, grp, df, tfm): 
        tfm.dfs[grp] = df.assign(DL=1)

# %% ../../nbs/handlers/fram_strait2025.ipynb #54443923
class AddLabCB(PerGroupCB):
    "Assign LAB MARIS ID for LIP, ETH Zürich"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(LAB=345)

# %% ../../nbs/handlers/fram_strait2025.ipynb #e00396ee
class FormatStationCB(PerGroupCB):
    "Cast STATION to str for the NetCDF4 string-typed station variable"
    def each_grp(self, grp, df, tfm):
        df["STATION"] = df["STATION"].astype(str)

# %% ../../nbs/handlers/fram_strait2025.ipynb #5fed230e
FS2025_KEYWORDS = [
    "Fram Strait","Greenland Sea","I-129","radionuclides","seawater","Arctic Ocean",
]

def get_attrs(tfm):
    "Retrieve global attributes for Fram Strait 2025"
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        KeyValuePairCB("keywords", ", ".join(FS2025_KEYWORDS)),
        KeyValuePairCB("publisher_postprocess_logs", ", ".join(tfm.logs)),
    ])()

# %% ../../nbs/handlers/fram_strait2025.ipynb #1784dfc3
def encode(
        dest=None,   # Output NetCDF file path
        src=None,    # Unused; Fram Strait 2025 fetches its data from RECORDS
        **kwargs     # Additional arguments
        ):
    "Fram Strait 2025 iodine-129 seawater radionuclide data, encoded to MARIS NetCDF4 format"
    dfs = load_data()
    tfm = Transformer(dfs, cbs=[
        RenameColsCB(),
        ParseDateTimeCB(),
        AddDepthCB(),
        AddNuclideCB(),
        AddValueCB(),
        AddUnitCB(),
        AddUncertCB(),
        AddDetectionLimitCB(),
        AddLabCB(),
        SanitizeLonLatCB(),
        EncodeTimeCB(),
        AddSampleIDCB(col_provider="SMP_ID_PROVIDER"),
        FormatStationCB()
        ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, dest_fname=dest,
                            global_attrs=get_attrs(tfm))
    encoder.encode()
