# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/fram_strait2025.ipynb.

# %% auto #0
__all__ = ['RECORDS', 'fname_out', 'src_dir', 'META_COLS', 'VAL_COLS', 'NUCLIDE_LUT', 'UNIT_LUT', 'STATIC_METADATA',
           'FS2025_KEYWORDS', 'load_data', 'RenameColsCB', 'ParseDateTimeCB', 'AddUnknownDepthCB', 'MeltCB',
           'ParseNuclideUnitCB', 'AuditDropNullCB', 'SetValueCB', 'MultiGateCB', 'FormatStationCB', 'get_attrs',
           'encode']

# %% ../../nbs/handlers/fram_strait2025.ipynb #d541866d
from fastcore.all import *
import pandas as pd
import numpy as np
import requests
import io

from marisco.callbacks import (
    PerGroupCB, Transformer, EncodeTimeCB,
    SanitizeLonLatCB, RemapCB, AddSampleIDCB
)
from marisco.metadata import (
    GlobAttrsFeeder, BboxCB, DepthRangeCB,
    TimeRangeCB, KeyValuePairCB
)
from ..encoders import NetCDFEncoder
from ..nc2csv import to_csv

# %% ../../nbs/handlers/fram_strait2025.ipynb #585e1b91
RECORDS = {
    "FS2025_i129": {
        "url": "https://zenodo.org/records/20761832/files/FS2025_i129.csv?download=1",
    },
}

fname_out = "Fram_Strait_2025.nc"
src_dir = None

# %% ../../nbs/handlers/fram_strait2025.ipynb #4f8d0cf6
def load_data(
    recs=None,  # Optional record mapping; defaults to all RECORDS
) -> dict:
    "Fetch Fram Strait CSV records and return one combined SEAWATER DataFrame."
    recs = recs or RECORDS
    parts = []

    for record in recs.values():
        resp = requests.get(record["url"], timeout=60)
        resp.raise_for_status()

        df = pd.read_csv(
            io.BytesIO(resp.content),
            encoding="utf-8-sig",
        )
        parts.append(df)

    return {"SEAWATER": pd.concat(parts, ignore_index=True)}

# %% ../../nbs/handlers/fram_strait2025.ipynb #4a497743
class RenameColsCB(PerGroupCB):
    "Map FS2025 provider columns to MARIS standard names."
    grps = ["SEAWATER"]

    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.rename(columns={
            "Station": "STATION",
            "Latitude_degN": "LAT",
            "Longitude_degE": "LON",
            "PracticalSalinity": "SAL",
            "Temperature_degC": "TEMP",
            "Sample_ID": "SMP_ID_PROVIDER",
        })

# %% ../../nbs/handlers/fram_strait2025.ipynb #e5342c85
class ParseDateTimeCB(PerGroupCB):
    "Parse FS2025 collection date into a UTC TIME value."
    grps = ["SEAWATER"]

    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(
            TIME=pd.to_datetime(df["Date"], format="%Y-%m-%d", utc=True)
        ).drop(columns="Date")

# %% ../../nbs/handlers/fram_strait2025.ipynb #49e473f3
class AddUnknownDepthCB(PerGroupCB):
    "Set sampling depth to -1 because FS2025 provides pressure, not depth in metres."
    grps = ["SEAWATER"]

    def each_grp(self, grp, df, tfm):
        df["SMP_DEPTH"] = -1.0

# %% ../../nbs/handlers/fram_strait2025.ipynb #909ce60c
META_COLS = ["Cruise", "STATION", "SMP_ID_PROVIDER", "LAT", "LON", "TIME", "SMP_DEPTH", "TEMP", "SAL"]
VAL_COLS = ["I129_at_l"]
NUCLIDE_LUT = {"I129": 28}
UNIT_LUT = {"at_l": 12}
STATIC_METADATA = {"LAB": 0}  # 分析機関が判明したら、そのMARIS LAB IDへ変更

# %% ../../nbs/handlers/fram_strait2025.ipynb #32428840
class MeltCB(PerGroupCB):
    "Reshape wide value/uncertainty columns into long format (Cartesian-product safe)."
    def __init__(self, meta_cols, val_cols, val_name='VALUE', unc_name='UNC', grps=None):
        store_attr(); self.grps = self.grps or ['SEAWATER']

    def each_grp(self, grp, df, tfm):
        df = df.assign(_SOURCE_ROW=df.index)
        vals = df.melt(id_vars=[*self.meta_cols, '_SOURCE_ROW'], value_vars=self.val_cols, var_name='nuclide_raw', value_name=self.val_name)
        if unc_cols := [f'unc_{c}' for c in self.val_cols if f'unc_{c}' in df.columns]:
            uncs = df.melt(id_vars=['_SOURCE_ROW'], value_vars=unc_cols, value_name=self.unc_name)
            uncs['nuclide_raw'] = uncs['variable'].str.removeprefix('unc_')
            vals = vals.merge(uncs[['_SOURCE_ROW', 'nuclide_raw', self.unc_name]], on=['_SOURCE_ROW', 'nuclide_raw'], how='left')
        else:
            vals[self.unc_name] = pd.NA
        tfm.dfs[grp] = vals.drop(columns=['_SOURCE_ROW']).reset_index(drop=True)


class ParseNuclideUnitCB(PerGroupCB):
    "Parse 'nuclide_raw' into NUCLIDE and UNIT columns using rsplit."
    def __init__(self, grps=None): self.grps = grps or ['SEAWATER']

    def each_grp(self, grp, df, tfm):
        parts = df['nuclide_raw'].str.rsplit('_at_', n=1, expand=True)
        tfm.dfs[grp] = df.assign(NUCLIDE=parts[0], UNIT='at_' + parts[1]).drop(columns=['nuclide_raw'])


class AuditDropNullCB(PerGroupCB):
    "Audit and drop rows with missing required values explicitly."
    def __init__(self, cols: list, grps=None):
        store_attr(); self.grps = self.grps or ['SEAWATER']

    def each_grp(self, grp, df, tfm):
        clean_df = df.dropna(subset=self.cols)
        if (n := len(df) - len(clean_df)) > 0:
            msg = f"[Audit] {grp}: Dropping {n} row(s) missing {self.cols}"
            print(msg); tfm.logs.append(msg)
        tfm.dfs[grp] = clean_df.reset_index(drop=True)


class SetValueCB(PerGroupCB):
    "Assign constant metadata dictionary."
    def __init__(self, constants: dict, grps=None):
        store_attr(); self.grps = self.grps or ['SEAWATER']

    def each_grp(self, grp, df, tfm):
        for k, v in self.constants.items(): df[k] = v
        tfm.dfs[grp] = df

# %% ../../nbs/handlers/fram_strait2025.ipynb #8e04ebd5
class MultiGateCB(PerGroupCB):
    "Fail-fast pre-RemapCB gate: every non-null value in each `col_src` must be a known key in its paired LUT."
    def __init__(self,
                 lut_pairs: dict,  # {col_src: lut} pairs to validate before RemapCB resolves them
                 grps: list=None,  # Groups to process (None = all)
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        for col_src, lut in self.lut_pairs.items():
            if unknown := set(df[col_src].dropna()) - set(lut):
                raise ValueError(
                    f"MultiGateCB: {grp}.{col_src} has unmapped value(s) {sorted(map(str, unknown))} "
                    f"not present in the lookup table. Known keys: {sorted(map(str, lut))}"
                )

# %% ../../nbs/handlers/fram_strait2025.ipynb #e00396ee
class FormatStationCB(PerGroupCB):
    "Cast STATION to str for the NetCDF4 string-typed station variable."
    grps = ["SEAWATER"]

    def each_grp(self, grp, df, tfm):
        df["STATION"] = df["STATION"].astype(str)

# %% ../../nbs/handlers/fram_strait2025.ipynb #5fed230e
FS2025_KEYWORDS = [
    "Fram Strait","Greenland Sea","I-129","radionuclides","seawater","Arctic Ocean",
]

def get_attrs(tfm):
    "Retrieve global attributes for Fram Strait 2025."
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        KeyValuePairCB("keywords", ", ".join(FS2025_KEYWORDS)),
        KeyValuePairCB("publisher_postprocess_logs", ", ".join(tfm.logs)),
    ])()

# %% ../../nbs/handlers/fram_strait2025.ipynb #1784dfc3
def encode(fname_out=None  # Output NetCDF file path; defaults to fname_out
            ):
    "Encode Fram Strait 2025 data to NetCDF4."
    fname_out = fname_out or globals().get("fname_out", "Fram_Strait_2025.nc")
    dfs = load_data()
    tfm = Transformer(dfs, cbs=[
        RenameColsCB(),ParseDateTimeCB(),AddUnknownDepthCB(),
        MeltCB(META_COLS, VAL_COLS),
        ParseNuclideUnitCB(),
        AuditDropNullCB(["VALUE"]),
        MultiGateCB(lut_pairs={"NUCLIDE": NUCLIDE_LUT, "UNIT": UNIT_LUT}),
        RemapCB(lut=NUCLIDE_LUT, col_remap="NUCLIDE", col_src="NUCLIDE"),
        RemapCB(lut=UNIT_LUT, col_remap="UNIT", col_src="UNIT"),
        SetValueCB(constants=STATIC_METADATA),
        SanitizeLonLatCB(),
        AuditDropNullCB(["TIME"]),
        EncodeTimeCB(),AddSampleIDCB(col_provider="SMP_ID_PROVIDER"),
        FormatStationCB(),
    ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, dest_fname=fname_out,
                            global_attrs=get_attrs(tfm))
    encoder.encode()
