"""Docs: https://franckalbinet.github.io/mariscohandlers/general.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/general.ipynb.

from __future__ import annotations
from pathlib import Path
from ..callbacks.core import PipelineState, run_pipeline
from .pipeline.loader import HandlerConfig, PluginSpec, load_data, gap_check
from .pipeline.writer import write_netcdf

__all__ = ['resolve_callback', 'build_phase_pipelines', 'build_core_pipeline', 'encode']


def resolve_callback(spec: PluginSpec, yaml_dir: Path = None):
    "Return the CB *class* (not yet instantiated) for the given PluginSpec."
    return spec.resolve(yaml_dir)


def _load_plugin(spec: PluginSpec, yaml_dir: Path = None):
    "Fail-Fast dynamic import: resolve class then instantiate with spec.args."
    cls = resolve_callback(spec, yaml_dir=yaml_dir)
    return cls(**spec.args)


def _load_plugin_fn(spec: PluginSpec, yaml_dir: Path = None):
    "Fail-Fast dynamic import of a plain function (not instantiated); for custom loaders."
    return spec.resolve_fn(yaml_dir)


def _call_loader(cfg: HandlerConfig, yaml_dir: Path = None):
    "Resolve the configured loader and execute it with cfg plus any declared loader args."
    if not cfg.loader:
        return load_data(cfg)
    loader_fn = _load_plugin_fn(cfg.loader, yaml_dir=yaml_dir)
    return loader_fn(cfg, **cfg.loader.args)


def build_phase_pipelines(cfg: HandlerConfig) -> tuple[list, list]:
    "Split the standard core chain into pre-lossy and post-lossy phases for deep Gate 2."
    from marisco.callbacks import (
        RenameColsCB, SoftParseDateTimeCB, SoftMeltWideNuclidesCB,
        SoftConvertUnitCB, SoftRemapCB, AddSampleIDCB,
        _GuardedEncodeTimeCB, _GuardedSanitizeLonLatCB,
    )

    merged = cfg.model_copy(update={
        "rename": {**cfg.columns, **cfg.rename},
        "dt_format": cfg.time_format or cfg.dt_format,
    })
    col_provider = next((v for v in merged.rename.values() if v.endswith('_PROVIDER')), None)

    pre_lossy = [
        RenameColsCB(mapping=merged.rename, string_cast=merged.string_cast),
        SoftParseDateTimeCB(col_date=merged.col_date, col_time=merged.col_time, fmt=merged.dt_format),
        SoftMeltWideNuclidesCB(spec=[s.model_dump() for s in merged.melt_spec]),
        *[SoftConvertUnitCB(rule=r.model_dump()) for r in merged.unit_conversions],
        SoftRemapCB(col_src='NUCLIDE', col_remap='NUCLIDE', lut=merged.nuclide_lut),
        SoftRemapCB(col_src='UNIT',    col_remap='UNIT',    lut=merged.unit_lut),
        SoftRemapCB(col_src='LAB',     col_remap='LAB',     lut=merged.lab_lut),
        SoftRemapCB(col_src='NUCLIDE', col_remap='AREA',    lut={}, default_val=merged.area_default),
    ]
    post_lossy = [
        _GuardedSanitizeLonLatCB(),
        _GuardedEncodeTimeCB(),
        AddSampleIDCB(col_provider=col_provider),
    ]
    return pre_lossy, post_lossy


def build_core_pipeline(cfg: HandlerConfig) -> list:
    "Auto-assemble the standard core CB chain with topology guards."
    pre_lossy, post_lossy = build_phase_pipelines(cfg)
    return [*pre_lossy, *post_lossy]


def encode(yaml_path: str | Path, fname_out: str = None) -> None:
    "Encode any YAML-configured dataset to MARIS NetCDF4 in a pure, phase-aware pipeline."
    from marisco.callbacks import LowerStripNameCB
    yaml_path = Path(yaml_path)
    yaml_dir = yaml_path.parent
    cfg = HandlerConfig.from_yaml(yaml_path)
    gap_check(cfg)
    if fname_out:
        cfg = cfg.model_copy(update={"fname_out": fname_out})

    dfs = _call_loader(cfg, yaml_dir=yaml_dir)
    state = PipelineState(dfs=dfs)
    normalize_cbs = [LowerStripNameCB(col_src=s, col_dst=d) for s, d in cfg.normalize_case.items()]
    pre_lossy, post_lossy = build_phase_pipelines(cfg)

    pre_chain = [
        *normalize_cbs,
        *[_load_plugin(s, yaml_dir=yaml_dir) for s in cfg.pre_cbs],
        *pre_lossy,
    ]
    run_pipeline(state, pre_chain)
    gap_check(cfg, state.dfs)

    post_chain = [
        *post_lossy,
        *[_load_plugin(s, yaml_dir=yaml_dir) for s in cfg.post_cbs],
    ]
    run_pipeline(state, post_chain)
    write_netcdf(state, cfg)
