"""Docs: https://franckalbinet.github.io/mariscohandlers/general.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/general.ipynb.

# %% ../../nbs/handlers/general.ipynb #d3398dc1
from __future__ import annotations
import importlib
from pathlib import Path
from ..callbacks.core import PipelineState, run_pipeline
from .pipeline.loader  import HandlerConfig, PluginSpec, load_data, gap_check
from .pipeline.writer  import write_netcdf


# %% auto #0
__all__ = ['build_core_pipeline', 'encode']

# %% ../../nbs/handlers/general.ipynb #717fbb3a
def _load_plugin(spec: PluginSpec):
    "Fail-Fast dynamic import: ImportError/AttributeError raised before pipeline starts."
    module_path, class_name = spec.path.rsplit(".", 1)
    cls = getattr(importlib.import_module(module_path), class_name)
    return cls(**spec.args)

def _load_plugin_fn(spec: PluginSpec):
    "Fail-Fast dynamic import of a plain function (not instantiated); for custom loaders."
    module_path, fn_name = spec.path.rsplit(".", 1)
    return getattr(importlib.import_module(module_path), fn_name)

def build_core_pipeline(cfg: HandlerConfig) -> list:
    "Auto-assemble the standard core CB chain with topology guards; EncodeTimeCB/SanitizeLonLatCB degrade to Null-Object when their required columns are absent."
    from marisco.callbacks import (
        RenameColsCB, SoftParseDateTimeCB, SoftMeltWideNuclidesCB,
        SoftConvertUnitCB, SoftRemapCB, EncodeTimeCB, SanitizeLonLatCB, AddSampleIDCB,
        _GuardedEncodeTimeCB, _GuardedSanitizeLonLatCB,
    )


    # Merge columns shorthand (S-7c) with legacy rename; time_format hint wins over dt_format
    merged = cfg.model_copy(update={
        "rename":    {**cfg.columns, **cfg.rename},
        "dt_format": cfg.time_format or cfg.dt_format,
    })
    col_provider = next((v for v in merged.rename.values() if v.endswith('_PROVIDER')), None)

    return [
        RenameColsCB(mapping=merged.rename, string_cast=merged.string_cast),
        SoftParseDateTimeCB(col_date=merged.col_date, col_time=merged.col_time, fmt=merged.dt_format),
        SoftMeltWideNuclidesCB(spec=[s.model_dump() for s in merged.melt_spec]),
        *[SoftConvertUnitCB(rule=r.model_dump()) for r in merged.unit_conversions],
        SoftRemapCB(col_src='NUCLIDE', col_remap='NUCLIDE', lut=merged.nuclide_lut),
        SoftRemapCB(col_src='UNIT',    col_remap='UNIT',    lut=merged.unit_lut),
        SoftRemapCB(col_src='LAB',     col_remap='LAB',     lut=merged.lab_lut),
        SoftRemapCB(col_src='NUCLIDE', col_remap='AREA',    lut={}, default_val=merged.area_default),
        _GuardedSanitizeLonLatCB(),
        _GuardedEncodeTimeCB(),
        AddSampleIDCB(col_provider=col_provider),
    ]

def encode(yaml_path: str | Path, fname_out: str = None) -> None:
    "Encode any YAML-configured dataset to MARIS NetCDF4 in a pure, single-pass pipeline."
    from marisco.callbacks import LowerStripNameCB
    cfg = HandlerConfig.from_yaml(yaml_path)
    gap_check(cfg)
    if fname_out:
        cfg = cfg.model_copy(update={"fname_out": fname_out})
    loader  = _load_plugin_fn(cfg.loader) if cfg.loader else load_data
    dfs     = loader(cfg)
    # normalize_case CBs run FIRST (before pre_cbs) to satisfy topology: e.g. nuclide→NUCLIDE
    # must exist before any pre_cb that reads NUCLIDE (such as HelcomNuclideRemapCB).
    normalize_cbs = [LowerStripNameCB(col_src=s, col_dst=d) for s, d in cfg.normalize_case.items()]
    chain   = [*normalize_cbs,
               *[_load_plugin(s) for s in cfg.pre_cbs],
               *build_core_pipeline(cfg),
               *[_load_plugin(s) for s in cfg.post_cbs]]
    state   = PipelineState(dfs=dfs)
    run_pipeline(state, chain)
    write_netcdf(state, cfg)
