"""Current-state notebook template for new handler authoring under `nbs/handlers/`.

Docs: https://franckalbinet.github.io/mariscohandlers/handler_template.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/handler_template.ipynb.

# %% auto #0
__all__ = ['TemplateCB', 'load_data', 'build_pipeline', 'get_attrs', 'encode']

# %% ../../nbs/handlers/handler_template.ipynb #6933fd47
from pathlib import Path
from typing import Any, Dict, Iterable, Optional


# %% ../../nbs/handlers/handler_template.ipynb #bc52abd5
class TemplateCB:
    """Minimal callback scaffold for reusable transformation stages."""

    def __call__(self, df):
        return df


# %% ../../nbs/handlers/handler_template.ipynb #ef84b6e0
def load_data(src, **kwargs):
    """Load provider-specific input data for the handler template."""

    return {
        "src": Path(src),
        "provider_options": dict(kwargs),
    }


# %% ../../nbs/handlers/handler_template.ipynb #81fe8983
def build_pipeline(callbacks: Optional[Iterable[Any]] = None):
    """Return the ordered callback pipeline for a handler implementation."""

    return list(callbacks) if callbacks is not None else [TemplateCB()]


# %% ../../nbs/handlers/handler_template.ipynb #074d6c36
def get_attrs(dataset_name: str = "handler-template", **metadata) -> Dict[str, Any]:
    """Build a minimal metadata payload for template-based handlers."""

    attrs = {
        "dataset_name": dataset_name,
        "template_stage": "current-state",
    }
    attrs.update(metadata)
    return attrs


# %% ../../nbs/handlers/handler_template.ipynb #8b0eb4a4
def encode(fname_in, fname_out, **kwargs):
    """Template encode entrypoint for notebook-authored handlers."""

    loaded = load_data(fname_in, **kwargs)
    return {
        "fname_in": Path(fname_in),
        "fname_out": Path(fname_out),
        "attrs": get_attrs(),
        "pipeline": build_pipeline(),
        "loaded": loaded,
    }

