# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/_jois_draft.ipynb.

# %% auto #0
__all__ = ['RECORDS', 'fname_out', 'load_data', 'norm_cols', 'extract_scales', 'apply_scales', 'MeltJOISCB', 'ConvertU238CB']

# %% ../../nbs/handlers/_jois_draft.ipynb #de238e47
from fastcore.all import *
import pandas as pd
import numpy as np
import re
import requests
import zipfile
import io

from ..callbacks import (PerGroupCB, Callback, Transformer, EncodeTimeCB,
                                SanitizeLonLatCB, RemapCB, AddSampleIDCB)
from ..metadata import (GlobAttrsFeeder, BboxCB, DepthRangeCB, TimeRangeCB,
                               ZoteroCB, KeyValuePairCB)
from ..configs import get_lut
from ..encoders import NetCDFEncoder
from .titanica_fram_strait import ParseDateTimeCB, RenameAndSelectCB

# %% ../../nbs/handlers/_jois_draft.ipynb #a95c067a
RECORDS = {
    2021: {'url': 'https://zenodo.org/records/18880401/files/annabel-payne/BGOS-JOIS-2021-v1.0.1.zip?download=1'},
    2022: {'url': 'https://zenodo.org/records/18880777/files/annabel-payne/BGOS-JOIS-2022-v1.0.1.zip?download=1'},
    2023: {'url': 'https://zenodo.org/records/18880591/files/annabel-payne/BGOS-JOIS-2023-v1.0.zip?download=1'},
    2024: {'url': 'https://zenodo.org/records/18880497/files/annabel-payne/BGOS-JOIS-2024-v1.0.1.zip?download=1'},
}
fname_out = '../../_data/output/jois.nc'

# %% ../../nbs/handlers/_jois_draft.ipynb #a95c067a
RECORDS = {
    2021: {'url': 'https://zenodo.org/records/18880401/files/annabel-payne/BGOS-JOIS-2021-v1.0.1.zip?download=1'},
    2022: {'url': 'https://zenodo.org/records/18880777/files/annabel-payne/BGOS-JOIS-2022-v1.0.1.zip?download=1'},
    2023: {'url': 'https://zenodo.org/records/18880591/files/annabel-payne/BGOS-JOIS-2023-v1.0.zip?download=1'},
    2024: {'url': 'https://zenodo.org/records/18880497/files/annabel-payne/BGOS-JOIS-2024-v1.0.1.zip?download=1'},
}
fname_out = '../../_data/output/jois.nc'

# %% ../../nbs/handlers/_jois_draft.ipynb #20208de8
def load_data(url, # Zenodo ZIP download URL
              ) -> dict:
    "Fetch JOIS ZIP from Zenodo, extract and parse the Excel file; returns dict keyed by sample type."
    r = requests.get(url, timeout=60); r.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
        xl_name = next(n for n in z.namelist() if n.lower().endswith(('.xlsx', '.xls')))
        df = pd.ExcelFile(io.BytesIO(z.read(xl_name))).parse(sheet_name=0)
    print(f'Shape  : {df.shape}')
    print(f'Columns: {df.columns.tolist()}')
    return {'SEAWATER': df}

# %% ../../nbs/handlers/_jois_draft.ipynb #688248d5
def norm_cols(cols):
    "Normalise column names: strip scale-factor suffixes like ( x 10^7) or (x 10^6)."
    return [re.sub(r'\s*\([^)]*\)\s*', '', c).strip() for c in cols]

# %% ../../nbs/handlers/_jois_draft.ipynb #3d0da9dc
def load_data(url, # Zenodo ZIP download URL
              ) -> dict:
    "Fetch JOIS ZIP from Zenodo, extract and parse the Excel file; returns dict keyed by sample type."
    r = requests.get(url, timeout=60); r.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
        xl_name = next(n for n in z.namelist() if n.lower().endswith(('.xlsx', '.xls')))
        df = pd.ExcelFile(io.BytesIO(z.read(xl_name))).parse(sheet_name=0)
    # Normalise column names
    cols = list(df.columns)
    cols = norm_cols(cols)
    # The 2021 dataset has ( x 10^6) as a leading column name — it's actually the Cruise name
    if cols[0] == '': cols[0] = 'Cruise'
    df.columns = cols
    print(f'Shape  : {df.shape}')
    print(f'Columns: {df.columns.tolist()}')
    return {'SEAWATER': df}

# %% ../../nbs/handlers/_jois_draft.ipynb #6d02b5b8
def extract_scales(cols):
    "Return {col: factor} for columns with `( x 10^N)` suffix in original names."
    return {re.sub(r'\s*\([^)]*\)\s*', '', c).strip(): 10**int(m.group(1))
            for c in cols if (m := re.search(r'\(\s*x\s*10\^(\d+)\)', c))}

# %% ../../nbs/handlers/_jois_draft.ipynb #41e8824b
def apply_scales(df, scales):
    "Multiply columns in df by their scale factor."
    for col, factor in scales.items():
        if col in df.columns: df[col] *= factor
    return df

# %% ../../nbs/handlers/_jois_draft.ipynb #126899bb
def load_data(url, # Zenodo ZIP download URL
              ) -> dict:
    "Fetch JOIS ZIP from Zenodo, extract and parse the Excel file; returns dict keyed by sample type."
    r = requests.get(url, timeout=60); r.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
        xl_name = next(n for n in z.namelist() if n.lower().endswith(('.xlsx', '.xls')))
        df = pd.ExcelFile(io.BytesIO(z.read(xl_name))).parse(sheet_name=0)
    # Normalise column names and apply scale factors
    cols = list(df.columns)
    scales = extract_scales(cols)
    cols = norm_cols(cols)
    if cols[0] == '': cols[0] = 'Cruise'
    df.columns = cols
    df = apply_scales(df, scales)
    print(f'Shape  : {df.shape}')
    print(f'Columns: {df.columns.tolist()}')
    return {'SEAWATER': df}

# %% ../../nbs/handlers/_jois_draft.ipynb #81ad1165
def extract_scales(cols):
    "Return {col: factor} for columns with `( x 10^N)` suffix in original names, excluding empty-string results."
    return {k: 10**int(m.group(1)) for c in cols 
            if (m := re.search(r'\(\s*x\s*10\^(\d+)\)', c)) 
            and (k := re.sub(r'\s*\([^)]*\)\s*', '', c).strip())}

# %% ../../nbs/handlers/_jois_draft.ipynb #b87808f9
def apply_scales(df, scales):
    "Multiply columns in df by their scale factor."
    for col, factor in scales.items():
        if col in df.columns: df[col] *= factor
    # 2023 U236_at_kg is missing its ( x 10^6) suffix but values are in same scale
    if any('U236' in c and c.endswith('_l') for c in scales):
        for c in ['U236_at_kg', 'unc_U236_at_kg']:
            if c in df.columns and c not in scales: df[c] *= 1e6
    return df

# %% ../../nbs/handlers/_jois_draft.ipynb #f9b09a66
def load_data(recs=None, # Optional dict of year->record; defaults to all RECORDS
              ) -> dict:
    "Fetch all JOIS records from Zenodo, align column names, apply scale factors, and return a single `SEAWATER` DataFrame."
    recs = recs or RECORDS
    parts = []
    for r in recs.values():
        resp = requests.get(r['url'], timeout=60); resp.raise_for_status()
        with zipfile.ZipFile(io.BytesIO(resp.content)) as z:
            xl_name = next(n for n in z.namelist() if n.lower().endswith(('.xlsx', '.xls')))
            df = pd.ExcelFile(io.BytesIO(z.read(xl_name))).parse(sheet_name=0)
        cols = list(df.columns)
        scales = extract_scales(cols)
        cols = norm_cols(cols)
        if cols[0] == '': cols[0] = 'Cruise'
        df.columns = cols
        df = apply_scales(df, scales)
        parts.append(df)
    return {'SEAWATER': pd.concat(parts, ignore_index=True)}

# %% ../../nbs/handlers/_jois_draft.ipynb #5751c1f1
class MeltJOISCB(Callback):
    "Reshape JOIS wide nuclide columns to long format."
    def __init__(self, meta_cols, val_cols, val_name='VALUE', unc_name='UNC'):
        store_attr()
    def __call__(self, tfm):
        df = tfm.dfs['SEAWATER']
        vals = df.melt(id_vars=self.meta_cols, value_vars=self.val_cols,
                       var_name='nuclide_raw', value_name=self.val_name)
        uncs = df.melt(id_vars=self.meta_cols,
                       value_vars=[f'unc_{c}' for c in self.val_cols],
                       value_name=self.unc_name)
        uncs['nuclide_raw'] = uncs['variable'].str.replace('unc_', '', regex=False)
        out = vals.merge(uncs[self.meta_cols + ['nuclide_raw', self.unc_name]],
                         on=self.meta_cols + ['nuclide_raw'])
        out.dropna(subset=self.val_name, inplace=True)
        out['NUCLIDE'] = out['nuclide_raw'].str.split('_at_').str[0]
        out['UNIT']    = 'at_' + out['nuclide_raw'].str.split('_at_').str[1]
        del out['nuclide_raw']
        tfm.dfs['SEAWATER'] = out

# %% ../../nbs/handlers/_jois_draft.ipynb #b787ee45
class ConvertU238CB(PerGroupCB):
    "Convert U238 from ppb to atoms/kg using Avogadro's number."
    def __init__(self, grps=['SEAWATER']): store_attr()
    def each_grp(self, grp, df, tfm):
        m = df['NUCLIDE'] == 64
        factor = 1e-6 / 238.0 * 6.02214076e23
        df.loc[m, 'VALUE'] *= factor
        df.loc[m, 'UNC']   *= factor
        df.loc[m, 'UNIT']   = 9
