# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/jois.ipynb.

# %% auto #0
__all__ = ['RECORDS', 'fname_out', 'src_dir', 'META_COLS', 'U238_PPB_TO_AT_KG', 'JOIS_COL_LUT', 'UNIT_CONV_LUT',
           'COL_SCALE_OVERRIDES', 'NUCLIDE_LUT', 'UNIT_LUT', 'LAB_ETH_LIP', 'AREA_BEAUFORT_SEA', 'JOIS_KEYWORDS',
           'norm_cols', 'load_data', 'RenameColsCB', 'ParseDateTimeCB', 'MeltNuclideColsCB', 'get_attrs', 'encode']

# %% ../../nbs/handlers/jois.ipynb #d541866d
from fastcore.all import *
import pandas as pd
import numpy as np
import re
import requests
import zipfile
import io

from ..callbacks import (PerGroupCB, Callback, Transformer, EncodeTimeCB,
                                SanitizeLonLatCB, RemapCB, AddSampleIDCB)
from ..metadata import GlobAttrsFeeder, ZoteroCB, BboxCB, DepthRangeCB, TimeRangeCB, KeyValuePairCB
from ..encoders import NetCDFEncoder

# %% ../../nbs/handlers/jois.ipynb #585e1b91
RECORDS = {
    2021: {'url': 'https://zenodo.org/records/18880401/files/annabel-payne/BGOS-JOIS-2021-v1.0.1.zip?download=1'},
    2022: {'url': 'https://zenodo.org/records/18880777/files/annabel-payne/BGOS-JOIS-2022-v1.0.1.zip?download=1'},
    2023: {'url': 'https://zenodo.org/records/18880591/files/annabel-payne/BGOS-JOIS-2023-v1.0.zip?download=1'},
    2024: {'url': 'https://zenodo.org/records/18880497/files/annabel-payne/BGOS-JOIS-2024-v1.0.1.zip?download=1'},
}
fname_out = 'JOIS_Beaufort_Sea.nc'
src_dir   = None  # remote-only, no local files

# %% ../../nbs/handlers/jois.ipynb #ac122ce2
def norm_cols(cols  # Column names to normalise
    ) -> list:
    "Normalise column names: strip scale-factor suffixes like ( x 10^7) or (x 10^6)."
    return [re.sub(r'\s*\([^)]*\)\s*', '', c).strip() for c in cols]

# %% ../../nbs/handlers/jois.ipynb #4f8d0cf6
def load_data(
    recs=None, # Optional dict of year->record; defaults to all RECORDS
    ) -> dict:
    "Fetch all JOIS ZIP archives from Zenodo and return raw DataFrames with original column names intact."
    recs = recs or RECORDS
    parts = []
    for r in recs.values():
        resp = requests.get(r['url'], timeout=60); resp.raise_for_status()
        with zipfile.ZipFile(io.BytesIO(resp.content)) as z:
            xl_name = next(n for n in z.namelist() if n.lower().endswith(('.xlsx', '.xls')))
            df = pd.ExcelFile(io.BytesIO(z.read(xl_name))).parse(sheet_name=0)
        cols = list(df.columns)
        if norm_cols(cols)[0] == '': cols[0] = 'Cruise'  # 2021 ZIP: stray empty header in col 0
        df.columns = cols
        parts.append(df)
    return {'SEAWATER': pd.concat(parts, ignore_index=True)}


# %% ../../nbs/handlers/jois.ipynb #4a497743
class RenameColsCB(PerGroupCB):
    "Map JOIS provider CTD and sample columns to MARIS standard names."
    grps = ["SEAWATER"]
    def each_grp(self, grp, df, tfm):
        df.rename(columns={
            "Latitude_degN": "LAT", "Longitude_degE": "LON",
            "Depth_m": "SMP_DEPTH", "Temperature_degC": "TEMP",
            "Salinity_psu": "SAL", "Station": "STATION",
            "sample_number": "SMP_ID_PROVIDER",
        }, inplace=True)

# %% ../../nbs/handlers/jois.ipynb #e5342c85
class ParseDateTimeCB(PerGroupCB):
    "Combine JOIS Date and Time columns into a single UTC-aware TIME column."
    grps = ["SEAWATER"]
    def __init__(self, col_date="Date",  # Source date column name
                 col_time="Time"):       # Source time column name
        store_attr()
    def each_grp(self, grp, df, tfm):
        df["TIME"] = pd.to_datetime(
            df[self.col_date].astype(str) + "T" + df[self.col_time].astype(str),
            utc=True)
        df.drop(columns=[self.col_date, self.col_time], inplace=True)


# %% ../../nbs/handlers/jois.ipynb #909ce60c
# Columns kept as identifiers during the wide-to-long reshape
META_COLS = ['Cruise', 'STATION', 'SMP_ID_PROVIDER', 'LAT', 'LON',
             'TIME', 'Pressure_dbar', 'SMP_DEPTH', 'TEMP', 'SAL']


# %% ../../nbs/handlers/jois.ipynb #a1b2c3d4
# Convert U-238 from ppb to atoms/kg: ppb * 1e-9 * (1/238.05) * 6.02214076e23
U238_PPB_TO_AT_KG = 2.529_697e12

# Maps normalized column name -> (nuc_tok, src_unit_tok)
# Eliminates VAL_COLS enumeration + RenameNucColsCB naming shim + MeltJOISCB._at_ split
JOIS_COL_LUT = {
    'I129_at_kg':  ('I129',      'at_kg'),
    'I129_at_l':   ('I129',      'at_l'),
    'U236_at_kg':  ('U236',      'at_kg'),
    'U236_at_l':   ('U236',      'at_l'),
    'U238_ppb':    ('U238',      'ppb'),    # src unit; UNIT_CONV_LUT normalises to at_kg
    'U236_U238':   ('U236_U238', 'ratio'),  # src unit; UNIT_CONV_LUT normalises to at_ratio
}

# Maps src_unit_tok -> (maris_unit_tok, base_factor)
# Absorbs ConvertU238CB: ppb->at_kg factor lives here, not in a separate Callback
UNIT_CONV_LUT = {
    'at_kg':    ('at_kg',    1.0),
    'at_l':     ('at_l',     1.0),
    'at_ratio': ('at_ratio', 1.0),
    'ppb':      ('at_kg',    U238_PPB_TO_AT_KG),   # U238 ppb -> atoms/kg
    'ratio':    ('at_ratio', 1.0),
}

# Scale overrides for columns whose ( x 10^N) suffix is absent in the provider file.
# 2023 U236_at_kg: suffix absent; scale confirmed by at_l/at_kg density-ratio check (~1025 kg/m3).
# See FEEDBACK TO DATA PROVIDER callout above for full provenance.
COL_SCALE_OVERRIDES = {
    'U236_at_kg':     1e6,
    'unc_U236_at_kg': 1e6,
}


# %% ../../nbs/handlers/jois.ipynb #b2c3d4e5
class MeltNuclideColsCB(PerGroupCB):
    "Reshape JOIS nuclide columns from wide to long, scaling each value by its column-name suffix factor and unit-conversion factor in the same pass. COL_SCALE_OVERRIDES supplies factors for suffix-absent columns (e.g. 2023 U236_at_kg: factor 1e6 confirmed by at_l/at_kg density-ratio check, seawater density ~1025 kg/m3)."
    grps = ['SEAWATER']
    def __init__(self,
                 meta_cols,                  # Identifier columns to preserve
                 col_lut,                    # {normalized_col: (nuc_tok, src_unit_tok)}
                 unit_conv_lut,              # {src_unit_tok: (maris_unit_tok, base_factor)}
                 col_scale_overrides=None):  # {normalized_col: factor} for suffix-absent columns
        store_attr()
        self.col_scale_overrides = col_scale_overrides or {}
    def each_grp(self, grp, df, tfm):
        frames = []
        for col in list(df.columns):
            norm = re.sub(r'\s*\([^)]*\)\s*', '', col).strip()
            if norm not in self.col_lut or norm.startswith('unc_'): continue
            nuc_tok, src_unit_tok = self.col_lut[norm]
            m = re.search(r'\s*\(\s*x\s*10\^([+-]?\d+)\)', col)
            suffix_factor = 10**int(m.group(1)) if m else self.col_scale_overrides.get(norm, 1.0)
            maris_unit_tok, base_factor = self.unit_conv_lut[src_unit_tok]
            total_factor = suffix_factor * base_factor
            unc_raw = next((c for c in df.columns
                            if re.sub(r'\s*\([^)]*\)\s*', '', c).strip() == f'unc_{norm}'), None)
            sub = df[self.meta_cols + [col]].copy()
            sub.rename(columns={col: 'VALUE'}, inplace=True)
            sub['VALUE'] = sub['VALUE'] * total_factor
            sub['UNC'] = df[unc_raw].values * total_factor if unc_raw else np.nan
            sub['NUCLIDE'] = nuc_tok
            sub['UNIT'] = maris_unit_tok
            frames.append(sub)
        out = pd.concat(frames, ignore_index=True)
        out.dropna(subset=['VALUE'], inplace=True)
        tfm.dfs[grp] = out


# %% ../../nbs/handlers/jois.ipynb #8b39ea1c
# MARIS nuclide IDs confirmed via get_lut('NUCLIDE')
NUCLIDE_LUT = {'I129': 28, 'U236': 108, 'U238': 64, 'U236_U238': 131}

# MARIS unit IDs confirmed via get_lut('UNIT')
UNIT_LUT = {'at_kg': 9, 'at_l': 12, 'at_ratio': 6}

# ETH Zurich / LIP (Casacuberta group) lab ID -- confirmed via get_lut('LABS')
LAB_ETH_LIP = 345

# Beaufort Sea area ID -- confirmed via get_lut('AREAS')
AREA_BEAUFORT_SEA = 4256


# %% ../../nbs/handlers/jois.ipynb #5fed230e
# NetCDF global attributes
JOIS_KEYWORDS = ['Beaufort Sea', 'JOIS', 'I-129', 'U-236', 'U-238', 'radionuclides', 'seawater', 'Arctic']

def get_attrs(tfm):
    "Retrieve global attributes for the JOIS handler."
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        #INISCB('XXXXXXXX'),  # TODO: add INIS record id when available
        KeyValuePairCB('keywords', ', '.join(JOIS_KEYWORDS)),
        KeyValuePairCB('publisher_postprocess_logs', ', '.join(tfm.logs)),
    ])()

# %% ../../nbs/handlers/jois.ipynb #1784dfc3
def encode(fname_out=None  # Output NetCDF file path; defaults to fname_out
            ):
    "Encode JOIS data to NetCDF4."
    fname_out = fname_out or globals().get('fname_out', 'JOIS_Beaufort_Sea.nc')
    dfs = load_data()
    tfm = Transformer(dfs, cbs=[
        RenameColsCB(), ParseDateTimeCB(),
        MeltNuclideColsCB(META_COLS, JOIS_COL_LUT, UNIT_CONV_LUT, COL_SCALE_OVERRIDES),
        RemapCB(lut=NUCLIDE_LUT, col_remap='NUCLIDE', col_src='NUCLIDE'),
        RemapCB(lut=UNIT_LUT,    col_remap='UNIT',    col_src='UNIT'),
        RemapCB(lut={}, col_remap='LAB',  col_src='NUCLIDE', default_val=LAB_ETH_LIP),
        RemapCB(lut={}, col_remap='AREA', col_src='NUCLIDE', default_val=AREA_BEAUFORT_SEA),
        SanitizeLonLatCB(),
        EncodeTimeCB(),
        AddSampleIDCB(col_provider='SMP_ID_PROVIDER'),
    ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, dest_fname=fname_out,
                            global_attrs=get_attrs(tfm))
    encoder.encode()

