"""Docs: https://franckalbinet.github.io/marisco/handlers/ospar.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/ospar.ipynb.

# %% auto #0
__all__ = ['SOURCE_GROUPS', 'REQUIRED_COLUMNS', 'load_data', 'capture_source_cardinality']

# %% ../../nbs/handlers/ospar.ipynb #2b1c9a66
from pathlib import Path
from urllib.parse import quote

import pandas as pd

from ..configs import cache_path

SOURCE_GROUPS = {
    "Biota": "BIOTA",
    "Seawater": "SEAWATER",
}

REQUIRED_COLUMNS = {
    "BIOTA": {"id", "species"},
    "SEAWATER": {"id", "sampling depth"},
}


def _source_path(src_dir: str, fname: str) -> str:
    "Build a path to `fname` under `src_dir`, handling local paths and URLs distinctly."
    if src_dir.startswith(("http://", "https://")):
        return f"{src_dir.rstrip('/')}/{quote(fname)}"
    return str(Path(src_dir) / fname)


def load_data(
    src_dir,
    smp_types=SOURCE_GROUPS,  # Sample types to load
    use_cache: bool = False,  # If True, read from the cache directory instead of `src_dir`
    save_to_cache: bool = False,  # Save to cache
) -> dict:
    "Load OSPAR source CSVs by sample type."
    src_dir = str(cache_path()) if use_cache else src_dir
    data = {}

    for prefix, smp_type in smp_types.items():
        fname = f"{prefix} data.csv"
        df = pd.read_csv(_source_path(src_dir, fname)).rename(str.lower, axis="columns")

        missing = REQUIRED_COLUMNS[smp_type] - set(df.columns)
        if missing:
            raise ValueError(
                f"OSPAR {smp_type} missing required columns: {sorted(missing)}"
            )

        if save_to_cache:
            df.to_csv(Path(cache_path()) / fname, index=False)

        data[smp_type] = df

    return data

def capture_source_cardinality(
    dfs: dict, # Source DataFrames keyed by OSPAR group, as returned by `load_data()`
) -> dict: # Detached snapshot: group -> source measurement row count
    "Capture a detached source-measurement-count snapshot for the production OSPAR BIOTA/SEAWATER boundary."
    expected = set(SOURCE_GROUPS.values())
    actual = set(dfs)
    if actual != expected:
        missing = expected - actual
        unexpected = actual - expected
        parts = []
        if missing:
            parts.append(f"missing: {sorted(missing)}")
        if unexpected:
            parts.append(f"unexpected: {sorted(unexpected)}")
        raise ValueError(f"OSPAR source cardinality groups mismatch ({'; '.join(parts)})")

    not_dataframes = {
        grp: type(df).__name__ for grp, df in dfs.items() if not isinstance(df, pd.DataFrame)
    }
    if not_dataframes:
        raise TypeError(f"OSPAR source cardinality expects DataFrames, got: {not_dataframes}")

    return {grp: len(df) for grp, df in dfs.items()}

