"""Docs: https://franckalbinet.github.io/marisco/handlers/ospar.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/ospar.ipynb.

# %% auto #0
__all__ = ['SOURCE_GROUPS', 'REQUIRED_COLUMNS', 'load_data']

# %% ../../nbs/handlers/ospar.ipynb #2b1c9a66
from pathlib import Path

import pandas as pd

from ..configs import cache_path

SOURCE_GROUPS = {
    "Biota": "BIOTA",
    "Seawater": "SEAWATER",
}

REQUIRED_COLUMNS = {
    "BIOTA": {"id", "species"},
    "SEAWATER": {"id", "sampling depth"},
}


def load_data(
    src_dir,
    smp_types=SOURCE_GROUPS,  # Sample types to load
    use_cache: bool = False,  # Use cache
    save_to_cache: bool = False,  # Save to cache
) -> dict:
    "Load OSPAR source CSVs by sample type."
    src_dir = str(cache_path()) if use_cache else src_dir
    data = {}

    for prefix, smp_type in smp_types.items():
        # GitHub raw URLs need spaces percent-encoded; harmless for local paths too.
        fname = f"{prefix} data.csv".replace(" ", "%20")
        df = pd.read_csv(f"{src_dir}/{fname}").rename(str.lower, axis="columns")

        missing = REQUIRED_COLUMNS[smp_type] - set(df.columns)
        if missing:
            raise ValueError(
                f"OSPAR {smp_type} missing required columns: {sorted(missing)}"
            )

        if save_to_cache:
            df.to_csv(Path(cache_path()) / fname, index=False)

        data[smp_type] = df

    return data
