"""Docs: https://franckalbinet.github.io/mariscohandlers/pipeline/loader.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/handlers/pipeline/loader.ipynb.

# %% ../../../nbs/handlers/pipeline/loader.ipynb #6eadfec0
from __future__ import annotations
import io
import importlib
import importlib.util
from pathlib import Path
from typing import Annotated, Optional, Union
import requests
import yaml
import pandas as pd
from pydantic import BaseModel, Field, ConfigDict, TypeAdapter


# %% auto #0
__all__ = ['PluginSpecModel', 'BasePluginSpec', 'LegacyPathPluginSpec', 'NamePluginSpec', 'FilePluginSpec', 'PluginSpec',
           'MeltEntry', 'UnitConversionCfg', 'HandlerConfig', 'load_data', 'gap_check']

# %% ../../../nbs/handlers/pipeline/loader.ipynb #1f01e56c
# Modules scanned (in order) when spec.name is used; first hit wins.
_SHARED_SCAN_MODULES = [
    "marisco.callbacks.shared",
    "marisco.callbacks.core",
]

class BasePluginSpec(BaseModel):
    "External Callback injection spec with polymorphic resolution."
    model_config = ConfigDict(populate_by_name=True)
    path: Optional[str] = None
    name: Optional[str] = None
    file: Optional[str] = None
    class_: Optional[str] = Field(None, alias="class")
    args: dict = Field(default_factory=dict)

    def resolve(self, yaml_dir: Path = None):
        raise NotImplementedError

    def resolve_fn(self, yaml_dir: Path = None):
        raise ValueError("Custom loader PluginSpec must use 'path:' (function, not class).")

class LegacyPathPluginSpec(BasePluginSpec):
    "Legacy fully-qualified dotted import path."
    path: str

    def resolve(self, yaml_dir: Path = None):
        module_path, class_name = self.path.rsplit(".", 1)
        return getattr(importlib.import_module(module_path), class_name)

    def resolve_fn(self, yaml_dir: Path = None):
        module_path, fn_name = self.path.rsplit(".", 1)
        return getattr(importlib.import_module(module_path), fn_name)

class NamePluginSpec(BasePluginSpec):
    "Shorthand callback name auto-resolved from shared/core modules."
    name: str

    def resolve(self, yaml_dir: Path = None):
        for mod_path in _SHARED_SCAN_MODULES:
            mod = importlib.import_module(mod_path)
            if hasattr(mod, self.name):
                return getattr(mod, self.name)
        raise ImportError(
            f"Callback '{self.name}' not found in {_SHARED_SCAN_MODULES}. "
            "Use the full 'path:' form to specify a non-shared callback."
        )

class FilePluginSpec(BasePluginSpec):
    "Local file import relative to the YAML directory."
    file: str
    class_: str = Field(alias="class")

    def resolve(self, yaml_dir: Path = None):
        if yaml_dir is None:
            raise ValueError("yaml_dir is required for file-based plugin loading")
        file_path = (Path(yaml_dir) / self.file).resolve()
        if not file_path.exists():
            raise FileNotFoundError(f"Plugin file not found: {file_path}")
        mod_spec = importlib.util.spec_from_file_location("_marisco_local_cb", file_path)
        mod = importlib.util.module_from_spec(mod_spec)
        mod_spec.loader.exec_module(mod)
        if not hasattr(mod, self.class_):
            raise AttributeError(f"Class '{self.class_}' not found in {file_path}")
        return getattr(mod, self.class_)

PluginSpecModel = Annotated[
    Union[LegacyPathPluginSpec, NamePluginSpec, FilePluginSpec],
    Field(union_mode="smart"),
]
_PLUGIN_SPEC_ADAPTER = TypeAdapter(PluginSpecModel)

class PluginSpec:
    "Backward-compatible factory for polymorphic plugin specs."

    def __new__(cls, *args, **kwargs):
        data = args[0] if args else kwargs
        return _PLUGIN_SPEC_ADAPTER.validate_python(data)

    @classmethod
    def model_validate(cls, data):
        return _PLUGIN_SPEC_ADAPTER.validate_python(data)

class MeltEntry(BaseModel):
    "One wide-to-long mapping entry: value column, uncertainty column, nuclide, unit, and lab."
    val:     str
    unc:     str
    nuclide: str
    unit:    str
    lab:     str

class UnitConversionCfg(BaseModel):
    "Single unit-conversion rule with its physical factor and optional metadata."
    nuclide:     str
    src_unit:    str
    dst_unit:    str
    factor:      float
    factor_name: str = ""
    comment:     str = ""

class HandlerConfig(BaseModel):
    "Complete handler configuration loaded from a YAML data-contract file."
    # handler
    module_name: str
    title:       str = ""
    description: str = ""
    # data_source
    url:       str
    fname_out: str
    zenodo_id: str = ""
    fmt:       str = "csv"
    # rename_cols (legacy) + declarative columns shorthand (S-7c)
    rename:      dict[str, str] = Field(default_factory=dict)
    string_cast: list[str]      = Field(default_factory=list)
    columns:     dict[str, str] = Field(default_factory=dict)  # provider_col → MARIS_col, merged into rename at pipeline build time
    # case normalisation: {src_col: dst_col} → LowerStripNameCB auto-assembled before pre_cbs (S-7c)
    normalize_case: dict[str, str] = Field(default_factory=dict)
    # parse_datetime
    col_date:    Optional[str] = None
    col_time:    Optional[str] = None
    dt_format:   str           = "%Y-%m-%d"
    time_format: Optional[str] = None  # explicit format hint; overrides dt_format when set
    # melt
    meta_cols: list[str]             = Field(default_factory=list)
    melt_spec: list[MeltEntry]       = Field(default_factory=list)
    # unit_conversions
    unit_conversions: list[UnitConversionCfg] = Field(default_factory=list)
    # nomenclatures (all optional — empty dict/0 → Null-Object no-ops in build_core_pipeline)
    nuclide_lut:   dict[str, int] = Field(default_factory=dict)
    unit_lut:      dict[str, int] = Field(default_factory=dict)
    lab_lut:       dict[str, int] = Field(default_factory=dict)
    lab_constants: dict[str, str] = Field(default_factory=dict)
    area_default:  int            = 0
    # output
    keywords: list[str] = Field(default_factory=list)
    # plugin injection: custom loader + pre/post standard core pipeline
    loader:   Optional[PluginSpecModel] = None
    pre_cbs:  list[PluginSpecModel]     = Field(default_factory=list)
    post_cbs: list[PluginSpecModel]     = Field(default_factory=list)

    @classmethod
    def from_yaml(cls, path: str | Path) -> "HandlerConfig":
        "Load and validate a handler YAML config; raises ValidationError on schema mismatch."
        raw      = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        h, ds    = raw["handler"], raw["data_source"]
        nom      = raw.get("nomenclatures", {})   # optional: absent → all LUTs default to {}
        ren      = raw.get("rename_cols", {})
        pdt      = raw.get("parse_datetime", {})
        mlt      = raw.get("melt", {})
        loader_raw = raw.get("loader", None)
        return cls(
            module_name      = h["module_name"],
            title            = h.get("title", ""),
            description      = h.get("description", "").strip(),
            url              = ds["url"],
            fname_out        = ds["fname_out"],
            zenodo_id        = ds.get("zenodo_id", ""),
            fmt              = ds.get("format", "csv"),
            rename           = ren.get("mapping", {}),
            string_cast      = ren.get("string_cast", []),
            columns          = raw.get("columns", {}),
            normalize_case   = raw.get("normalize_case", {}),
            col_date         = pdt.get("col_date"),
            col_time         = pdt.get("col_time"),
            dt_format        = pdt.get("format", "%Y-%m-%d"),
            time_format      = raw.get("time_format"),
            meta_cols        = mlt.get("meta_cols", []),
            melt_spec        = mlt.get("spec", []),
            unit_conversions = raw.get("unit_conversions", []),
            nuclide_lut      = nom.get("nuclide_lut", {}),
            unit_lut         = nom.get("unit_lut", {}),
            lab_lut          = nom.get("lab_lut", {}),
            lab_constants    = nom.get("lab_constants", {}),
            area_default     = nom.get("area_default", 0),
            keywords         = raw.get("output", {}).get("keywords", []),
            loader           = loader_raw,
            pre_cbs          = raw.get("pre_cbs", []),
            post_cbs         = raw.get("post_cbs", []),
        )


# %% ../../../nbs/handlers/pipeline/loader.ipynb #fb3b4a2b
def load_data(cfg: HandlerConfig, grp: str = "SEAWATER") -> dict[str, pd.DataFrame]:
    "Fetch raw CSV/TSV from cfg.url and return {grp: DataFrame}."
    r = requests.get(cfg.url, timeout=60)
    r.raise_for_status()
    sep = "	" if cfg.fmt == "tsv" else ","
    return {grp: pd.read_csv(io.BytesIO(r.content), sep=sep)}

# %% ../../../nbs/handlers/pipeline/loader.ipynb #e53c62ea
_MARIS_REQUIRED = frozenset({"LAT", "LON", "TIME", "NUCLIDE", "VALUE", "UNC", "UNIT"})
_MELT_PROVIDES  = frozenset({"NUCLIDE", "VALUE", "UNC", "UNIT"})

def gap_check(cfg: HandlerConfig) -> None:
    "Fail-Fast: raise ValueError listing missing MARIS columns and printing skeleton CBs."
    if cfg.pre_cbs: return  # plugin chain is responsible for column provision
    # columns (S-7c shorthand) and rename both contribute mapped destination names
    all_rename = {**cfg.columns, **cfg.rename}
    available = (set(all_rename.values())
                 | (_MELT_PROVIDES if cfg.melt_spec else set())
                 | ({"TIME"}       if cfg.col_date  else set()))
    gaps = _MARIS_REQUIRED - available
    if not gaps:
        return
    skeleton = "\n\n".join(
        f"class Fill{g}CB(PerGroupCB):\n"
        f"    \"TODO: provide {g} — add to columns/rename_cols or as a standalone CB.\"\n"
        f"    grps = [\'SEAWATER\']\n"
        f"    def each_grp(self, grp, df, tfm): df[\'{g}\'] = None  # FIXME"
        for g in sorted(gaps)
    )
    print(f"\n⚠  GAP in {cfg.title!r} — missing MARIS columns: {sorted(gaps)}\n\n{skeleton}\n")
    raise ValueError(f"YAML spec missing mappings for: {sorted(gaps)}")
