"""Docs: https://franckalbinet.github.io/marisco/handlers/pipeline/template_loader.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/handlers/pipeline/template_loader.ipynb.

# %% ../../../nbs/handlers/pipeline/template_loader.ipynb #template-loader-export
from __future__ import annotations

import pandas as pd

from .contracts import HandlerConfig


def load_and_cleanse(cfg: HandlerConfig) -> dict[str, pd.DataFrame]:
    """Load one provider file and return physically clean group DataFrames.

    Copy this template into ``config/handlers/<dataset>_loader.py`` and adapt only
    file-boundary concerns: file access, header cleanup, provider type parsing, and
    removal of physically empty records. Keep MARIS semantic mapping, melt rules,
    nomenclature LUTs, and measurement defaults in the dataset YAML contract.
    """
    # 1. Read the provider artifact from cfg.url (CSV, ZIP, XLSX, or another file format).
    # df = pd.read_excel(cfg.url, sheet_name="Measurements")

    # 2. Repair physical header issues before the declarative pipeline receives the frame.
    # df.columns = df.columns.astype(str).str.strip()

    # 3. Parse provider-native types needed to make the file structurally readable.
    # df["provider_timestamp"] = pd.to_datetime(df["provider_timestamp"], errors="raise")

    # 4. Remove records that are physically blank; do not create MARIS semantic columns here.
    # df = df.dropna(how="all").copy()

    # 5. Return clean provider-shaped frames. YAML performs semantic mapping afterwards.
    # return {"SEAWATER": df}
    raise NotImplementedError(
        "Adapt this Boundary Loader template for the provider file before configuring it in YAML."
    )


# %% auto #0
__all__ = ['load_and_cleanse']
