"""Docs: https://franckalbinet.github.io/mariscohandlers/pipeline/writer.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/handlers/pipeline/writer.ipynb.

from __future__ import annotations
import pandas as pd
from ...callbacks import Transformer, RenameColumnsCB, Callback
from ...metadata import GlobAttrsFeeder, DepthRangeCB, TimeRangeCB, KeyValuePairCB
from ...encoders import NetCDFEncoder
from ...configs import NC_VARS
from .loader import HandlerConfig, _MARIS_REQUIRED

__all__ = ['write_netcdf']


class _SimpleBboxCB(Callback):
    """Compute geospatial bounding box from LAT/LON via pure pandas min/max.
    Replaces BboxCB (Shapely-free). WKT polygon delegated to DB server."""
    def __call__(self, obj):
        all_df = pd.concat(obj.dfs.values())
        obj.attrs.update({
            'geospatial_lat_min': str(all_df['LAT'].min()),
            'geospatial_lat_max': str(all_df['LAT'].max()),
            'geospatial_lon_min': str(all_df['LON'].min()),
            'geospatial_lon_max': str(all_df['LON'].max()),
        })


def write_netcdf(tfm: Transformer, cfg: HandlerConfig) -> None:
    "Encode transformed DataFrames to MARIS NetCDF4; KeyError on missing required MARIS columns."
    for grp, df in tfm.dfs.items():
        missing = _MARIS_REQUIRED - set(df.columns)
        if missing:
            raise KeyError(f"Group '{grp}' missing required MARIS columns: {sorted(missing)}")

    for grp in list(tfm.dfs):
        grp_guard = {k: k for k in NC_VARS if k in tfm.dfs[grp].columns}
        Transformer({grp: tfm.dfs[grp]}, cbs=[RenameColumnsCB(grp_guard)], inplace=True)()

    computed_attrs = GlobAttrsFeeder(tfm.dfs, cbs=[
        _SimpleBboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        KeyValuePairCB('keywords', ', '.join(cfg.keywords)),
        KeyValuePairCB('publisher_postprocess_logs', ', '.join(tfm.logs)),
    ])()
    global_attrs = {**cfg.global_attrs, **computed_attrs}
    NetCDFEncoder(tfm.dfs, dest_fname=cfg.fname_out, global_attrs=global_attrs).encode()
