"""Docs: https://franckalbinet.github.io/mariscohandlers/pipeline/writer.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/handlers/pipeline/writer.ipynb.

# %% ../../../nbs/handlers/pipeline/writer.ipynb #21a89f69
from __future__ import annotations
from ...callbacks import Transformer, RenameColumnsCB
from ...metadata import (GlobAttrsFeeder, BboxCB, DepthRangeCB,
                               TimeRangeCB, KeyValuePairCB)
from ...encoders import NetCDFEncoder
from ...configs import NC_VARS
from .loader import HandlerConfig, _MARIS_REQUIRED

# %% auto #0
__all__ = ['write_netcdf']

# %% ../../../nbs/handlers/pipeline/writer.ipynb #04ca11cb
def write_netcdf(tfm: Transformer, cfg: HandlerConfig) -> None:
    "Encode transformed DataFrames to MARIS NetCDF4; KeyError on missing required MARIS columns."
    # Phase 1 — Fail-Fast: required MARIS columns must be present in every group
    for grp, df in tfm.dfs.items():
        missing = _MARIS_REQUIRED - set(df.columns)
        if missing:
            raise KeyError(f"Group '{grp}' missing required MARIS columns: {sorted(missing)}")

    # Phase 2 — per-group RenameColumnsCB: drop non-NC_VARS noise columns in-place
    for grp in list(tfm.dfs):
        grp_guard = {k: k for k in NC_VARS if k in tfm.dfs[grp].columns}
        Transformer({grp: tfm.dfs[grp]}, cbs=[RenameColumnsCB(grp_guard)], inplace=True)()

    # GlobAttrsFeeder: spatial / temporal extents + provenance
    global_attrs = GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        KeyValuePairCB('keywords',                  ', '.join(cfg.keywords)),
        KeyValuePairCB('publisher_postprocess_logs', ', '.join(tfm.logs)),
    ])()

    NetCDFEncoder(tfm.dfs, dest_fname=cfg.fname_out, global_attrs=global_attrs).encode()
